# Generated by Django 6.0.4 on 2026-04-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolingrecipe',
            name='cutting_type',
            field=models.CharField(choices=[('to_liner', 'To Liner'), ('metal_to_metal', 'Metal to Metal'), ('score', 'Score'), ('special', 'Special')], default='to_liner', max_length=30),
        ),
        migrations.AlterField(
            model_name='toolingrecipe',
            name='shape_type',
            field=models.CharField(choices=[('rcr', 'RCR'), ('circle', 'Circle'), ('oval', 'Oval'), ('rectangle', 'Rectangle'), ('special', 'Special'), ('custom', 'Custom')], default='rcr', max_length=30),
        ),
    ]
