# Generated by Django 6.0.4 on 2026-05-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0002_toolingrecipe_cutting_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolingrecipe',
            name='internal_perf_cutting_type',
            field=models.CharField(blank=True, choices=[('to_liner', 'To Liner'), ('through_liner', 'Through Liner')], default='', help_text='Only used when internal perf is selected.', max_length=30),
        ),
        migrations.AddField(
            model_name='toolingrecipe',
            name='internal_perf_notes',
            field=models.TextField(blank=True, default='', help_text='Internal perf notes. Only used when internal perf is selected.'),
        ),
        migrations.AddField(
            model_name='toolingrecipe',
            name='internal_perf_option',
            field=models.CharField(blank=True, choices=[('none', 'No Perf'), ('perf', 'Perf')], default='none', help_text='Internal perf inside the label. Defaults to No Perf.', max_length=20),
        ),
        migrations.AddField(
            model_name='toolingrecipe',
            name='internal_perf_tpi',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Internal perf TPI. Only used when internal perf is selected.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='toolingrecipe',
            name='perf_notes',
            field=models.TextField(blank=True, default='', help_text='External perf notes. Only used when external perf is selected.'),
        ),
        migrations.AddField(
            model_name='toolingrecipe',
            name='perf_option',
            field=models.CharField(blank=True, choices=[('none', 'No Perf'), ('perf', 'Perf')], default='none', help_text='External perf between labels. Defaults to No Perf.', max_length=20),
        ),
        migrations.AlterField(
            model_name='toolingrecipe',
            name='tpi',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='External perf TPI. Only used when external perf is selected.', max_digits=6, null=True),
        ),
    ]
