# Generated by Django 6.0.4 on 2026-05-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0003_toolingrecipe_internal_perf_cutting_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolingrecipetool',
            name='tool_role',
            field=models.CharField(choices=[('top', 'Top / Main'), ('undercut', 'Undercut'), ('perf', 'Perf'), ('other', 'Other')], default='top', max_length=30),
        ),
    ]
