# Generated by Django 6.0.4 on 2026-05-06 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0004_toolingrecipetool_tool_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexdie',
            name='shape_type',
            field=models.CharField(choices=[('rcr', 'RCR'), ('circle', 'Circle'), ('oval', 'Oval'), ('rectangle', 'Rectangle'), ('special', 'Special')], default='rcr', max_length=30),
        ),
        migrations.AlterField(
            model_name='toolingrecipe',
            name='shape_type',
            field=models.CharField(choices=[('rcr', 'RCR'), ('circle', 'Circle'), ('oval', 'Oval'), ('rectangle', 'Rectangle'), ('special', 'Special')], default='rcr', max_length=30),
        ),
        migrations.CreateModel(
            name='JobTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=80, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('product_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('in_production', 'In Production'), ('finishing', 'Finishing'), ('complete', 'Complete'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('rush', 'Rush'), ('hot', 'Hot')], default='normal', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('material_width_inches', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('material_length_feet', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('requested_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('produced_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('finishing_type', models.CharField(choices=[('none', 'None'), ('rewind', 'Rewind'), ('sheet', 'Sheet'), ('fanfold', 'Fanfold'), ('pack', 'Pack'), ('inspect', 'Inspect'), ('custom', 'Custom')], default='none', max_length=30)),
                ('finishing_notes', models.TextField(blank=True)),
                ('operator', models.CharField(blank=True, max_length=100)),
                ('suboperator', models.CharField(blank=True, max_length=100)),
                ('production_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('press', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_tickets', to='tooling.press')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_tickets', to='tooling.toolingrecipe')),
                ('recipe_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_tickets', to='tooling.toolingrecipeoption')),
            ],
            options={
                'ordering': ['-scheduled_date', 'ticket_number'],
            },
        ),
        migrations.CreateModel(
            name='FinishedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('material_width_inches', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('material_length_feet', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('face_type', models.CharField(blank=True, max_length=100)),
                ('liner_type', models.CharField(blank=True, max_length=100)),
                ('liner_serial_number', models.CharField(blank=True, max_length=80)),
                ('face_serial_number', models.CharField(blank=True, max_length=80)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit', models.CharField(choices=[('roll', 'Roll'), ('case', 'Case'), ('label', 'Label'), ('lf', 'Linear Feet'), ('each', 'Each')], default='roll', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('allocated', 'Allocated'), ('shipped', 'Shipped'), ('on_hold', 'On Hold'), ('scrapped', 'Scrapped')], default='available', max_length=20)),
                ('operator', models.CharField(blank=True, max_length=100)),
                ('suboperator', models.CharField(blank=True, max_length=100)),
                ('run_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_inventory', to='tooling.toolinglocation')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_inventory', to='tooling.toolingrecipe')),
                ('recipe_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_inventory', to='tooling.toolingrecipeoption')),
                ('job_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_inventory', to='tooling.jobticket')),
            ],
            options={
                'ordering': ['-run_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('face', 'Face'), ('liner', 'Liner'), ('adhesive', 'Adhesive'), ('silicone', 'Silicone')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('serial_number', models.CharField(blank=True, max_length=80)),
                ('lot_number', models.CharField(blank=True, max_length=80)),
                ('face_type', models.CharField(blank=True, max_length=100)),
                ('liner_type', models.CharField(blank=True, max_length=100)),
                ('adhesive_type', models.CharField(blank=True, max_length=100)),
                ('silicone_type', models.CharField(blank=True, max_length=100)),
                ('width_inches', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('length_feet', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit', models.CharField(choices=[('lf', 'Linear Feet'), ('msi', 'MSI'), ('lbs', 'Pounds'), ('gal', 'Gallons'), ('roll', 'Roll'), ('each', 'Each')], default='lf', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('allocated', 'Allocated'), ('in_use', 'In Use'), ('on_hold', 'On Hold'), ('depleted', 'Depleted'), ('scrapped', 'Scrapped')], default='available', max_length=20)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_materials', to='tooling.toolinglocation')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_materials', to='tooling.supplier')),
            ],
            options={
                'ordering': ['material_type', 'name', 'serial_number'],
            },
        ),
        migrations.AddField(
            model_name='jobticket',
            name='adhesive_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adhesive_jobs', to='tooling.rawmaterialinventory'),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='face_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_jobs', to='tooling.rawmaterialinventory'),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='liner_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liner_jobs', to='tooling.rawmaterialinventory'),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='silicone_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='silicone_jobs', to='tooling.rawmaterialinventory'),
        ),
    ]
