# Generated by Django 6.0.4 on 2026-05-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0005_alter_flexdie_shape_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexdie',
            name='shape_type',
            field=models.CharField(choices=[('rcr', 'RCR'), ('circle', 'Circle'), ('oval', 'Oval'), ('rectangle', 'Rectangle'), ('special', 'Special'), ('custom', 'Custom')], default='rcr', max_length=30),
        ),
        migrations.AlterField(
            model_name='toolingrecipe',
            name='shape_type',
            field=models.CharField(choices=[('rcr', 'RCR'), ('circle', 'Circle'), ('oval', 'Oval'), ('rectangle', 'Rectangle'), ('special', 'Special'), ('custom', 'Custom')], default='rcr', max_length=30),
        ),
    ]
