# Generated by Django 6.0.4 on 2026-05-18 11:36

import tooling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0006_alter_flexdie_shape_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=tooling.models.job_ticket_image_upload_path),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='finishing_image',
            field=models.ImageField(blank=True, null=True, upload_to=tooling.models.job_ticket_image_upload_path),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='spec_image',
            field=models.ImageField(blank=True, null=True, upload_to=tooling.models.job_ticket_image_upload_path),
        ),
    ]
