# Generated by Django 6.0.4 on 2026-05-20 10:24

import tooling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0007_jobticket_cover_image_jobticket_finishing_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexdie',
            name='active_die_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flexdie',
            name='dieline_image',
            field=models.ImageField(blank=True, null=True, upload_to=tooling.models.flex_die_image_upload_path),
        ),
        migrations.AddField(
            model_name='flexdie',
            name='dieline_image_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='flexdie',
            name='manual_web_width',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flexdie',
            name='original_serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='flexdie',
            name='serial_numbers',
            field=models.TextField(blank=True, help_text='One serial number per line. Keeps a history of dies that have lived in this jacket.'),
        ),
        migrations.AddField(
            model_name='flexdie',
            name='target_die_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='flexdie',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('in_stock', 'In Stock'), ('in_use', 'In Use'), ('needs_ordered', 'Needs Ordered'), ('needs_repair', 'Needs Repair'), ('out_for_retool', 'Out for Retool'), ('retired', 'Retired'), ('missing', 'Missing')], default='in_stock', max_length=30),
        ),
        migrations.AlterField(
            model_name='toolinghistory',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('moved', 'Moved'), ('installed_on_press', 'Installed on Press'), ('removed_from_press', 'Removed from Press'), ('sent_to_supplier', 'Sent to Supplier'), ('returned_from_supplier', 'Returned from Supplier'), ('repair', 'Repair'), ('retool', 'Retool'), ('status_change', 'Status Change'), ('inspection', 'Inspection'), ('note', 'Note'), ('retired', 'Retired'), ('die_reorder_requested', 'Die Reorder Requested'), ('die_ordered', 'Die Ordered'), ('die_received', 'Die Received'), ('die_count_adjusted', 'Die Count Adjusted')], max_length=40),
        ),
    ]
