# Generated by Django 6.0.4 on 2026-05-27 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0009_add_multilevel_cutting_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=100)),
                ('customer_plate_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=220)),
                ('number_around', models.PositiveIntegerField(blank=True, null=True)),
                ('number_across', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_plates', to='tooling.toolingrecipe')),
            ],
            options={
                'ordering': ['recipe__name', 'plate_number'],
                'unique_together': {('recipe', 'plate_number')},
            },
        ),
        migrations.CreateModel(
            name='PrintStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_number', models.PositiveIntegerField(default=1)),
                ('station_plate_number', models.CharField(blank=True, max_length=100)),
                ('print_cylinder_tooth_count', models.PositiveIntegerField(blank=True, null=True)),
                ('anilox_gear_number', models.CharField(blank=True, max_length=80)),
                ('pms_color', models.CharField(blank=True, max_length=80)),
                ('color_type', models.CharField(choices=[('spot', 'Spot'), ('process', 'Process'), ('white', 'White'), ('varnish', 'Varnish'), ('coating', 'Coating'), ('other', 'Other')], default='spot', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('print_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='tooling.printplate')),
            ],
            options={
                'ordering': ['print_plate__recipe__name', 'print_plate__plate_number', 'station_number'],
                'unique_together': {('print_plate', 'station_number')},
            },
        ),
    ]
