# Generated by Django 6.0.4 on 2026-08-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0020_flexdierequest_toolinghistory_die_request_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexdie',
            name='corner_radius_inches',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='flexdie',
            name='compatible_presses',
            field=models.ManyToManyField(blank=True, help_text='Known/imported press compatibility. Exact production setups should still assign the mag and die through recipe tools.', related_name='direct_compatible_flex_dies', to='tooling.press'),
        ),
        migrations.AddField(
            model_name='flexdie',
            name='external_dieline_source',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='flexdie',
            name='external_dieline_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
