import {
  Activity,
  CalendarPlus,
  CheckCircle2,
  Factory,
  Gauge,
  History,
  Layers3,
  MapPin,
  PackageMinus,
  PackageCheck,
  Printer,
  Ruler,
  Scissors,
  Settings2,
  Shapes,
  ShieldCheck,
  Store,
  UploadCloud,
  Wrench,
} from "lucide-react";

export const choiceLists = {
  rawMaterialType: [
    ["liner", "Liner"],
    ["face", "Face"],
    ["adhesive", "Adhesive"],
    ["silicone", "Silicone"],
    ["coating", "Coating"],
    ["coated_stock", "Coated Stock"],
  ],

  rawMaterialStatus: [
    ["available", "Available"],
    ["scheduled", "Scheduled"],
    ["allocated", "Allocated"],
    ["in_use", "In Use"],
    ["on_hold", "On Hold"],
    ["depleted", "Depleted"],
    ["scrapped", "Scrapped"],
  ],

  rawMaterialUnit: [
    ["lf", "Linear Feet"],
    ["msi", "MSI"],
    ["lbs", "Pounds"],
    ["gal", "Gallons"],
    ["roll", "Roll"],
    ["each", "Each"],
  ],

  finishedInventoryStatus: [
    ["available", "Available"],
    ["allocated", "Allocated"],
    ["shipped", "Shipped"],
    ["on_hold", "On Hold"],
    ["scrapped", "Scrapped"],
  ],

  finishedInventoryUnit: [
    ["roll", "Roll"],
    ["carton", "Carton"],
    ["case", "Case"],
    ["label", "Label"],
    ["sheet", "Sheet"],
    ["each", "Each"],
  ],

  jobTicketStatus: [
    ["unscheduled", "Unscheduled"],
    ["draft", "Draft"],
    ["scheduled", "Scheduled"],
    ["in_production", "In Production"],
    ["finishing", "Finishing"],
    ["complete", "Complete"],
    ["on_hold", "On Hold"],
    ["cancelled", "Cancelled"],
  ],

  productionScheduleStatus: [
    ["unscheduled", "Unassigned"],
    ["scheduled", "Scheduled"],
    ["ready", "Ready"],
    ["running", "Running"],
    ["complete", "Complete"],
    ["on_hold", "On Hold"],
    ["cancelled", "Cancelled"],
  ],

  jobTicketPriority: [
    ["normal", "Normal"],
    ["rush", "Rush"],
    ["hot", "Hot"],
  ],

  finishingType: [
    ["rolls", "Rolls"],
    ["fanfold", "Fanfold"],
    ["sheeted", "Sheeted"],
  ],

  ticketUnitType: [
    ["label", "Label"],
    ["tag", "Tag"],
  ],

  ribbonType: [
    ["no_ribbon", "No Ribbon"],
    ["ribbon", "Ribbon"],
  ],

  laminateType: [
    ["no_laminate", "No Laminate"],
    ["laminate", "Laminate"],
  ],

  baggedType: [
    ["not_bagged", "Not Bagged"],
    ["bagged", "Bagged"],
  ],

  cartonLabelFormat: [
    ["standard", "Standard Carton"],
    ["dow_carton", "DOW Carton"],
    ["dow_closure", "DOW Closure"],
    ["customer_label", "Customer Label"],
    ["bcl", "BCL"],
    ["abe", "ABE"],
    ["clopay", "Clopay"],
    ["variable_barcode", "Variable Barcode"],
    ["camslide", "Camslide"],
  ],

  coaterStatus: [
    ["scheduled", "Scheduled"],
    ["running", "Running"],
    ["complete", "Complete"],
    ["on_hold", "On Hold"],
    ["void", "Void"],
  ],

  materialUsageType: [
    ["checkout", "Checked Out"],
    ["returned", "Returned"],
    ["qc_issue", "QC Issue"],
    ["coater", "Coater"],
    ["finished", "Finished Production"],
    ["shipped", "Shipped Finished Stock"],
    ["manual", "Manual Consumption"],
    ["scrap", "Scrap"],
    ["adjustment", "Adjustment"],
  ],

  printColorType: [
    ["spot", "Spot"],
    ["process", "Process"],
    ["white", "White"],
    ["varnish", "Varnish"],
    ["coating", "Coating"],
    ["other", "Other"],
  ],

  printStatus: [
    ["not_printed", "Not Printed"],
    ["queued", "Queued"],
    ["printed", "Printed"],
    ["reprint", "Needs Reprint"],
  ],

  windDirection: [
    ["", "Not Set"],
    ["1", "Wind 1"],
    ["2", "Wind 2"],
    ["3", "Wind 3"],
    ["4", "Wind 4"],
    ["5", "Wind 5"],
    ["6", "Wind 6"],
    ["7", "Wind 7"],
    ["8", "Wind 8"],
  ],

  bladeType: [
    ["standard", "Standard"],
    ["offset", "Offset"],
    ["skip", "Skip"],
    ["sheeter", "Sheeter"],
    ["custom", "Custom"],
  ],

  adhesiveType: [
    ["permanent", "Permanent"],
    ["removable", "Removable"],
    ["freezer", "Freezer"],
    ["aggressive", "Aggressive"],
    ["repositionable", "Repositionable"],
    ["custom", "Custom"],
  ],

  siliconeType: [
    ["standard", "Standard"],
    ["premium_release", "Premium Release"],
    ["tight_release", "Tight Release"],
    ["easy_release", "Easy Release"],
    ["custom", "Custom"],
  ],

  shapeType: [
    ["rcr", "RCR"],
    ["circle", "Circle"],
    ["oval", "Oval"],
    ["rectangle", "Rectangle"],
    ["special", "Special"],
    ["custom", "Custom"],
  ],

  layoutShapeType: [
    ["rcr", "RCR"],
    ["circle", "Circle"],
    ["rectangle", "Rectangle"],
    ["special", "Special"],
  ],

  toolRole: [
    ["top", "Top / Main"],
    ["undercut", "Undercut"],
    ["perf", "Perf"],
    ["other", "Other"],
  ],

  cuttingType: [
    ["to_liner", "To Liner"],
    ["metal_to_metal", "Metal to Metal"],
    ["score", "Score"],
    ["special", "Special"],
  ],

  labelCutType: [
    ["to_liner", "To Liner"],
    ["metal_to_metal", "Metal to Metal"],
    ["multilevel", "Multilevel"],
  ],

  perfOption: [
    ["none", "No Perf"],
    ["perf", "Perf"],
    ["sheeted", "Sheeted / Sheeter Cut"],
  ],

  internalPerfCuttingType: [
    ["to_liner", "To Liner"],
    ["through_liner", "Through Liner"],
  ],

  faceType: [
    ["paper", "Paper"],
    ["poly", "Poly"],
    ["bopp", "BOPP"],
    ["thermal_transfer", "Thermal Transfer"],
    ["direct_thermal", "Direct Thermal"],
    ["tag", "Tag"],
    ["custom", "Custom"],
  ],

  linerType: [
    ["paper", "Paper"],
    ["pet", "PET"],
    ["poly", "Poly"],
    ["none", "None"],
    ["custom", "Custom"],
  ],

  toolStatus: [
    ["ordered", "Ordered"],
    ["in_stock", "In Stock"],
    ["in_use", "In Use"],
    ["needs_ordered", "Needs Ordered"],
    ["available", "Available"],
    ["needs_repair", "Needs Repair"],
    ["out_for_retool", "Out for Retool"],
    ["out_for_repair", "Out for Repair"],
    ["retired", "Retired"],
    ["missing", "Missing"],
    ["inactive", "Inactive"],
  ],

  activeStatus: [
    ["active", "Active"],
    ["inactive", "Inactive"],
  ],

  setupType: [
    ["standard", "Standard"],
    ["undercut", "Undercut"],
    ["manual_custom", "Manual Custom"],
    ["experimental", "Experimental"],
  ],

  toolType: [
    ["flex_die", "Flex Die"],
    ["mag", "Mag"],
    ["perf_cylinder", "Perf Cylinder"],
    ["perf_blade_setup", "Perf Blade Setup"],
    ["manual_tooling", "Manual Tooling"],
    ["other", "Other"],
  ],

  locationType: [
    ["company", "Company"],
    ["shop", "Shop"],
    ["room", "Room"],
    ["rack", "Rack"],
    ["shelf", "Shelf"],
    ["position", "Position"],
    ["press", "Press"],
    ["supplier", "Supplier"],
    ["unknown", "Unknown"],
  ],
};

export const toolRoleChoices = choiceLists.toolRole;

const dimFields = [
  { name: "label_width_inches", label: "Width", type: "number", step: "0.0001" },
  { name: "label_length_inches", label: "Length", type: "number", step: "0.0001" },
  { name: "repeat_inches", label: "Repeat", type: "number", step: "0.0001" },
];

const linerDataTypeField = {
  name: "liner_type",
  label: "Liner",
  type: "select",
  choices: choiceLists.linerType,
  lookupRelation: "material-liners",
  lookupValueField: "name",
  lookupLabelFields: ["name", "code", "liner_pounds", "material_family"],
};

const baseMaterialColumns = [
  "name",
  "color",
  "liner_pounds",
  "is_active",
];

const componentMaterialTypes = ["liner", "face", "adhesive", "silicone", "coating"];

function choiceLabel(choices, value) {
  return choices.find(([choiceValue]) => choiceValue === value)?.[1] || value;
}

function materialDataTypeLabel(row) {
  return [
    row?.name || row?.material_family || row?.code || "Material",
    choiceLabel(choiceLists.rawMaterialType, row?.material_type),
  ].filter(Boolean).join(" - ");
}

function supplierField(recommendedSupplierTags, extra = {}) {
  const tags = Array.isArray(recommendedSupplierTags) ? recommendedSupplierTags : [recommendedSupplierTags].filter(Boolean);
  return {
    name: "supplier",
    label: "Supplier",
    type: "searchRelation",
    relation: "suppliers",
    searchable: true,
    recommendedSupplierTags: tags,
    maxResults: 500,
    searchFields: ["name", "tags", "phone", "email", "city", "state", "notes"],
    helpText: tags.length ? `Suppliers tagged ${tags.join(" or ")} are recommended first.` : undefined,
    ...extra,
  };
}

function finishedMaterialField(field) {
  return {
    ...field,
    showWhen: { material_type: "coated_stock" },
    clearWhenHidden: null,
  };
}

const finishedMaterialColumns = [
  "master_type_code",
  "inventory_total_feet",
  "allowed_face_material_summary",
  "allowed_liner_material_summary",
  "allowed_adhesive_material_summary",
  "gsm",
];

function componentRelationFields() {
  return [
    {
      name: "face_material",
      label: "Preferred Face Type",
      type: "searchRelation",
      relation: "materials",
      searchable: true,
      display: materialDataTypeLabel,
      groupByFamily: true,
      lookupFilters: { material_type: "face" },
      searchFields: ["code", "name", "company", "material_family", "gsm", "color", "notes"],
      section: "Preferred Defaults",
      helpText: "Default face type to use when scheduling. Allowed face types below control compatibility.",
    },
    {
      name: "liner_material",
      label: "Preferred Liner Type",
      type: "searchRelation",
      relation: "materials",
      searchable: true,
      display: materialDataTypeLabel,
      groupByFamily: true,
      lookupFilters: { material_type: "liner" },
      searchFields: ["code", "name", "company", "material_family", "liner_pounds", "gsm", "color", "notes"],
      section: "Preferred Defaults",
      helpText: "Default liner type to use when scheduling. Allowed liner types below control compatibility.",
    },
    {
      name: "adhesive_material",
      label: "Preferred Adhesive Type",
      type: "searchRelation",
      relation: "materials",
      searchable: true,
      display: materialDataTypeLabel,
      groupByFamily: true,
      lookupFilters: { material_type: "adhesive" },
      searchFields: ["code", "name", "company", "material_family", "gsm", "notes"],
      section: "Preferred Defaults",
      helpText: "Default adhesive type to use when scheduling. Allowed adhesive types below control compatibility.",
    },
    {
      name: "silicone_material",
      label: "Preferred Silicone Type",
      type: "searchRelation",
      relation: "materials",
      searchable: true,
      display: materialDataTypeLabel,
      groupByFamily: true,
      lookupFilters: { material_type: "silicone" },
      searchFields: ["code", "name", "company", "material_family", "gsm", "notes"],
      section: "Preferred Defaults",
      helpText: "Default silicone type to use when scheduling. Allowed silicone types below control compatibility.",
    },
    {
      name: "coating_material",
      label: "Preferred Coating / Varnish Type",
      type: "searchRelation",
      relation: "materials",
      searchable: true,
      display: materialDataTypeLabel,
      groupByFamily: true,
      lookupFilters: { material_type: "coating" },
      searchFields: ["code", "name", "company", "material_family", "gsm", "notes"],
      section: "Preferred Defaults",
      helpText: "Default coating type to use when scheduling. Allowed coating types below control compatibility.",
    },
    {
      name: "allowed_face_materials",
      label: "Allowed Face Types",
      type: "multiRelation",
      relation: "materials",
      display: materialDataTypeLabel,
      lookupFilters: { material_type: "face" },
      searchFields: ["code", "name", "company", "material_family", "gsm", "color", "notes"],
      section: "Compatibility",
      helpText: "All face types that can be used to make this finished raw material.",
    },
    {
      name: "allowed_liner_materials",
      label: "Allowed Liner Types",
      type: "multiRelation",
      relation: "materials",
      display: materialDataTypeLabel,
      lookupFilters: { material_type: "liner" },
      searchFields: ["code", "name", "company", "material_family", "liner_pounds", "gsm", "color", "notes"],
      section: "Compatibility",
      helpText: "All liner types that can be used to make this finished raw material.",
    },
    {
      name: "allowed_adhesive_materials",
      label: "Allowed Adhesive Types",
      type: "multiRelation",
      relation: "materials",
      display: materialDataTypeLabel,
      lookupFilters: { material_type: "adhesive" },
      searchFields: ["code", "name", "company", "material_family", "gsm", "notes"],
      section: "Compatibility",
      helpText: "All adhesive types that can be used to make this finished raw material.",
    },
    {
      name: "allowed_silicone_materials",
      label: "Allowed Silicone Types",
      type: "multiRelation",
      relation: "materials",
      display: materialDataTypeLabel,
      lookupFilters: { material_type: "silicone" },
      searchFields: ["code", "name", "company", "material_family", "gsm", "notes"],
      section: "Compatibility",
      helpText: "All silicone types that can be used to make this finished raw material.",
    },
    {
      name: "allowed_coating_materials",
      label: "Allowed Coating / Varnish Types",
      type: "multiRelation",
      relation: "materials",
      display: materialDataTypeLabel,
      lookupFilters: { material_type: "coating" },
      searchFields: ["code", "name", "company", "material_family", "gsm", "notes"],
      section: "Compatibility",
      helpText: "All coating or varnish types that can be used to make this finished raw material.",
    },
  ];
}

function materialFields(defaultType = "liner", hiddenType = false, namePlaceholder = "Material name") {
  const isFinishedRawMaterial = defaultType === "coated_stock";
  const isLiner = defaultType === "liner";

  return [
    { name: "material_type", label: "Material Type", type: "select", choices: choiceLists.rawMaterialType, required: true, defaultValue: defaultType, hidden: hiddenType },
    { name: "code", label: "Code", type: "text", placeholder: "Leave blank to auto-generate" },
    { name: "name", label: isFinishedRawMaterial ? "Description" : "Data Type", type: "text", required: true, placeholder: namePlaceholder },
    finishedMaterialField({
      name: "master_type",
      label: "Master Material Type",
      type: "searchRelation",
      relation: "material-master-types",
      searchable: true,
      searchFields: ["code", "name", "description"],
      helpText: "Finished construction family such as PM, PM/PET, PET, LPO, or LV. Component data types stay reusable across these families.",
    }),
    ...(isFinishedRawMaterial ? [
      finishedMaterialField({ name: "company", label: "Company", type: "text", placeholder: "Internal or supplier description" }),
    ] : []),
    { name: "liner_pounds", label: "Liner Pounds", type: "number", step: "0.01", showWhen: { material_type: "liner" }, clearWhenHidden: null },
    ...(isFinishedRawMaterial ? [
      finishedMaterialField({ name: "gsm", label: "Glue GSM", type: "number", step: "0.01" }),
      finishedMaterialField({ name: "material_family", label: "Material Family", type: "text", placeholder: "PM, PMDT, PET, LPO, LV..." }),
    ] : []),
    ...(isFinishedRawMaterial ? componentRelationFields().map(finishedMaterialField) : []),
    ...(!isLiner ? [{ name: "color", label: "Color", type: "text" }] : []),
    { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    { name: "notes", label: "Notes", type: "textarea" },
  ];
}

function materialSupplierOptionFields() {
  return [
    {
      name: "material",
      label: "Component Data Type",
      type: "searchRelation",
      relation: "materials",
      searchable: true,
      required: true,
      lookupFilters: { material_type: componentMaterialTypes },
      display: materialDataTypeLabel,
      searchFields: ["name", "material_type", "color", "notes"],
      maxResults: 500,
    },
    supplierField("material", {
      required: true,
      helpText: "Choose the supplier record. The supplier name comes from the Suppliers page.",
    }),
    { name: "option_name", label: "Option Description", type: "text", placeholder: "PM 3.5 mil coating" },
    { name: "supplier_item_number", label: "Supplier Item #", type: "text" },
    { name: "thickness_mil", label: "Thickness Mil", type: "number", step: "0.001" },
    { name: "width_inches", label: "Width", type: "number", step: "0.001" },
    { name: "length_feet", label: "Length", type: "number", step: "0.01" },
    { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    { name: "notes", label: "Notes", type: "textarea" },
  ];
}

const materialTypeResources = [
  { key: "material-coated-stock", label: "Materials", singular: "Material", materialType: "coated_stock", accent: "#38bdf8", placeholder: "PM 40# perm coated stock" },
  { key: "material-faces", label: "Face", singular: "Face Data Type", materialType: "face", accent: "#2dd4bf", placeholder: "PM, PMDT, PET, LPO, LV" },
  { key: "material-liners", label: "Liner", singular: "Liner Data Type", materialType: "liner", accent: "#a3e635", placeholder: "40#, 80#, clear PET" },
  { key: "material-adhesives", label: "Adhesive", singular: "Adhesive Data Type", materialType: "adhesive", accent: "#f97316", placeholder: "Permanent, removable, freezer" },
  { key: "material-silicone", label: "Silicone", singular: "Silicone Data Type", materialType: "silicone", accent: "#e879f9", placeholder: "Easy release silicone" },
];

export const resourceGroups = [
  { key: "production", label: "Production", defaultOpen: true },
  { key: "production-material", label: "Material", defaultOpen: true },
  { key: "inventory", label: "Inventory", defaultOpen: true },
  { key: "tooling", label: "Tooling", defaultOpen: false },
  { key: "plant", label: "Plant", defaultOpen: false },
  { key: "trace", label: "Trace", defaultOpen: false },
];

export const resources = [
  {
    key: "job-ticket-images",
    label: "Job Ticket Images",
    singular: "Job Ticket Image Permission",
    group: "production",
    icon: PackageCheck,
    permissionOnly: true,
    disableCreate: true,
    tagline: "Allows a role to view, upload, replace, and delete job ticket images.",
    columns: [],
    fields: [],
  },
  {
    key: "job-ticket-schedule",
    label: "Job Ticket Scheduling",
    singular: "Job Ticket Scheduling Permission",
    group: "production",
    icon: CalendarPlus,
    permissionOnly: true,
    disableCreate: true,
    tagline: "Allows a role to open the schedule form directly from a job ticket.",
    columns: [],
    fields: [],
  },
  {
    key: "job-ticket-editor",
    label: "Job Ticket Editor",
    singular: "Job Ticket Editor Permission",
    group: "production",
    icon: Settings2,
    permissionOnly: true,
    disableCreate: true,
    tagline: "Allows a role to open the job ticket editor and make job-ticket changes.",
    columns: [],
    fields: [],
  },
  {
    key: "job-ticket-change-approval",
    label: "Job Ticket Change Approval",
    singular: "Job Ticket Change Approval Permission",
    group: "production",
    icon: ShieldCheck,
    permissionOnly: true,
    disableCreate: true,
    tagline: "Allows a manager or admin to approve or reject recorded job ticket edits.",
    columns: [],
    fields: [],
  },
  {
    key: "job-ticket-events",
    endpoint: "job-ticket-events",
    label: "Job Ticket History",
    singular: "Job Ticket History Event",
    group: "trace",
    icon: History,
    permissionOnly: true,
    disableCreate: true,
    tagline: "Permanent job ticket timeline for creates, edits, schedule changes, and press assignment changes.",
    columns: [],
    fields: [],
  },
  {
    key: "job-ticket-usages",
    endpoint: "job-ticket-usages",
    label: "Job Ticket Usage",
    singular: "Job Ticket Usage",
    group: "trace",
    icon: History,
    permissionOnly: true,
    disableCreate: true,
    defaultOrdering: "-used_at",
    tagline: "Simple old-system usage records by date, job ticket, and quantity.",
    columns: [],
    fields: [],
  },
  {
    key: "data-import",
    label: "Data Import",
    singular: "Data Import",
    group: "trace",
    icon: UploadCloud,
    accent: "#0ea5e9",
    staticView: true,
    viewMode: "dataImport",
    disableCreate: true,
    tagline: "Import job tickets, flex dies, raw inventory, and inventory usage from CSV files.",
    columns: [],
    fields: [],
  },
  {
    key: "quote-material-admin",
    label: "Quote Material Setup",
    singular: "Quote Material Setup Permission",
    group: "production",
    icon: Layers3,
    permissionOnly: true,
    disableCreate: true,
    tagline: "Allows a role to view and edit the quote calculator finished material and raw material setup tabs.",
    columns: [],
    fields: [],
  },
  {
    key: "quote-approval",
    label: "Quote Approval",
    singular: "Quote Approval Permission",
    group: "production",
    icon: CheckCircle2,
    permissionOnly: true,
    disableCreate: true,
    tagline: "Allows a role to approve or reject saved quotes before they are treated as ready.",
    columns: [],
    fields: [],
  },

  {
    key: "quote-calculator",
    label: "Quote Calculator",
    singular: "Quote Calculator",
    group: "production",
    icon: Gauge,
    accent: "#0ea5e9",
    staticView: true,
    viewMode: "quoteCalculator",
    disableCreate: true,
    tagline: "Estimate label quote material cost from web width, lane count, auto repeat, MSI cost, waste, and margin.",
    columns: [],
    fields: [
      { name: "product_code", label: "TSM ID", type: "text", hidden: true },
      { name: "due_date", label: "Ship Date", type: "date", hidden: true },
      { name: "press_sequence", label: "Press Order #", type: "number", hidden: true },
      { name: "scheduled_by", label: "Scheduled By", type: "text", hidden: true },
    ],
  },

  {
    key: "live-footage",
    label: "Live Footage",
    singular: "Live Footage",
    group: "production",
    icon: Activity,
    accent: "#16a34a",
    staticView: true,
    viewMode: "liveFootage",
    disableCreate: true,
    tagline: "Realtime Firebase footage dashboard for press speed, shift totals, and the companywide footage goal.",
    columns: [],
    fields: [],
  },

  {
    key: "coater-operator",
    label: "Coater Operator",
    singular: "Coater Operator",
    group: "production",
    icon: Factory,
    accent: "#0f766e",
    staticView: true,
    viewMode: "coaterOperator",
    disableCreate: true,
    tagline: "Coater operator lineup for scheduled material runs, roll tags, and finished product jobs.",
    columns: [],
    fields: [],
  },

  {
    key: "customers",
    endpoint: "customers",
    label: "Customers",
    singular: "Customer",
    group: "production",
    icon: Store,
    accent: "#22c55e",
    defaultOrdering: "name",
    viewMode: "customers",
    tagline: "Customer command center for account details, quotes, job tickets, and order history.",
    columns: [
      "name",
      "customer_code",
      "contact_name",
      "city",
      "state",
      "phone",
      "email",
      "is_active",
    ],
    fields: [
      { name: "name", label: "Customer", type: "text", required: true, section: "Account" },
      { name: "customer_code", label: "Customer ID", type: "text", section: "Account" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true, section: "Account" },
      { name: "contact_name", label: "Primary Contact", type: "text", section: "Contact" },
      { name: "phone", label: "Phone", type: "text", section: "Contact" },
      { name: "email", label: "Email", type: "email", section: "Contact" },
      { name: "address_line_1", label: "Address Line 1", type: "text", section: "Address" },
      { name: "address_line_2", label: "Address Line 2", type: "text", section: "Address" },
      { name: "address_line_3", label: "Address Line 3", type: "text", section: "Address" },
      { name: "city", label: "City", type: "text", section: "Address" },
      { name: "state", label: "State", type: "text", section: "Address" },
      { name: "postal_code", label: "Zip / Postal", type: "text", section: "Address" },
      { name: "country", label: "Country", type: "text", section: "Address" },
      { name: "notes", label: "Notes", type: "textarea", section: "Notes" },
    ],
  },

  {
    key: "job-tickets",
    endpoint: "job-tickets",
    label: "Job Tickets",
    singular: "Job Ticket",
    group: "production",
    icon: Factory,
    accent: "#38bdf8",
    defaultOrdering: "-recent_usage_90d,ticket_number",
    viewMode: "jobTicketGallery",
    tagline: "Visual job packet gallery with the job image, job name, and key customer identifiers.",
    columns: [
      "customer_display",
      "customer_name",
      "job_name",
      "product_code",
      "description",
      "material_master_type_code",
      "label_width_inches",
      "label_length_inches",
      "repeat_inches",
      "cutting_type",
      "recipe_name",
      "box_item_number",
      "linked_box_item_number",
      "box_name",
      "core_item_number",
      "core_name",
      "finishing_type",
      "unit_type",
      "labels_per_unit",
      "units_per_carton",
      "fanfold_gear",
      "labels_per_fold",
      "ribbon",
      "laminate",
      "bagged",
    ],
    fields: [
      { name: "ticket_number", label: "Ticket #", type: "text", hidden: true },
      {
        name: "customer",
        label: "Customer",
        type: "searchRelation",
        relation: "customers",
        searchable: true,
        displayMode: "nameOnly",
        lookupPageSize: 1000,
        lookupFetchAll: true,
        searchFields: ["name", "customer_code", "contact_name", "phone", "email"],
      },
      { name: "customer_name", label: "Customer Name Override", type: "text", hidden: true },
      { name: "job_name", label: "Job Number", type: "text", required: true, placeholder: "Customer job number or description" },
      { name: "product_code", label: "TSM ID", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "box_item_number", label: "Legacy Box Item #", type: "text", helpText: "Old system text value. Use Box Link for the managed box record." },
      { name: "general_image", label: "General Image", type: "imageUpload", imageSlot: "general", requiresResourceAccess: "job-ticket-images" },
      { name: "general_image_description", label: "General Image Description", type: "textarea", hidden: true, requiresResourceAccess: "job-ticket-images" },
      { name: "spec_image", label: "Spec Image", type: "imageUpload", imageSlot: "spec", requiresResourceAccess: "job-ticket-images" },
      { name: "spec_image_description", label: "Spec Image Description", type: "textarea", hidden: true, requiresResourceAccess: "job-ticket-images" },
      { name: "finishing_image", label: "Finishing Image", type: "imageUpload", imageSlot: "finishing", requiresResourceAccess: "job-ticket-images" },
      { name: "finishing_image_description", label: "Finishing Image Description", type: "textarea", hidden: true, requiresResourceAccess: "job-ticket-images" },
      {
        name: "material_master_type",
        label: "Material Type",
        type: "searchRelation",
        relation: "material-master-types",
        searchable: true,
        maxResults: 250,
        searchFields: ["code", "name", "description"],
        helpText: "Material family used to match this job to coated-stock inventory.",
      },
      { name: "label_width_inches", label: "Label Width", type: "number", step: "0.0001", section: "Label Layout", sectionHint: "Match these values to the label layout library." },
      { name: "label_length_inches", label: "Label Length", type: "number", step: "0.0001", section: "Label Layout" },
      { name: "repeat_inches", label: "Label Repeat", type: "number", step: "0.0001", section: "Label Layout" },
      { name: "cutting_type", label: "Label Cutting Type", type: "select", choices: choiceLists.cuttingType, defaultValue: "to_liner", hidden: true },
      {
        name: "face_type",
        label: "Face Type",
        type: "select",
        choices: choiceLists.faceType,
        lookupRelation: "material-faces",
        lookupValueField: "name",
        lookupLabelFields: ["name", "code", "material_family"],
        section: "Label Layout",
      },
      { ...linerDataTypeField, label: "Liner Type", section: "Label Layout" },
      {
        name: "recipe",
        label: "Label Layout",
        type: "searchRelation",
        relation: "recipes",
        searchable: true,
        maxResults: 250,
        recommendFromJobLayout: true,
        section: "Label Layout",
        searchFields: ["name", "label_width_inches", "label_length_inches", "repeat_inches", "face_type", "liner_type", "shape_type", "cutting_type"],
      },
      {
        name: "box",
        label: "Box Link",
        type: "searchRelation",
        relation: "boxes",
        searchable: true,
        maxResults: 250,
        searchFields: ["name", "item_number", "supplier", "width_inches", "length_inches", "height_inches"],
      },
      {
        name: "core",
        label: "Core Link",
        type: "searchRelation",
        relation: "cores",
        searchable: true,
        maxResults: 250,
        searchFields: ["name", "item_number", "supplier", "core_size_inches"],
      },
      { name: "finishing_type", label: "Finishing", type: "select", choices: choiceLists.finishingType, defaultValue: "rolls" },
      { name: "unit_type", label: "Unit Type", type: "select", choices: choiceLists.ticketUnitType, defaultValue: "label" },
      {
        name: "labels_per_unit",
        label: "Labels per Unit",
        type: "number",
        dynamicLabel: (form) => {
          const noun = form.unit_type === "tag" ? "Tags" : "Labels";
          return form.finishing_type === "rolls" ? `${noun} per Roll` : `${noun} per Unit`;
        },
      },
      {
        name: "units_per_carton",
        label: "Units per Carton",
        type: "number",
        helpText: "Used as the quote quantity.",
        dynamicLabel: (form) => `${form.unit_type === "tag" ? "Tags" : "Labels"} / Carton`,
      },
      { name: "core_size_inches", label: "Core Size", type: "number", step: "0.0001", showWhen: { finishing_type: "rolls" }, clearWhenHidden: null },
      { name: "wind_direction", label: "Wind", type: "select", choices: choiceLists.windDirection, showWhen: { finishing_type: "rolls" }, clearWhenHidden: "" },
      { name: "fanfold_gear", label: "Fanfold Gear", type: "number", step: "1", showWhen: { finishing_type: "fanfold" }, clearWhenHidden: null },
      {
        name: "labels_per_fold",
        label: "Labels per Fold",
        type: "number",
        step: "1",
        showWhen: { finishing_type: "fanfold" },
        clearWhenHidden: null,
        dynamicLabel: (form) => `${form.unit_type === "tag" ? "Tags" : "Labels"} / Fold`,
      },
      { name: "ribbon", label: "Ribbon", type: "select", choices: choiceLists.ribbonType, defaultValue: "no_ribbon" },
      { name: "laminate", label: "Laminate", type: "select", choices: choiceLists.laminateType, defaultValue: "no_laminate" },
      { name: "bagged", label: "Bagged", type: "select", choices: choiceLists.baggedType, defaultValue: "not_bagged" },
      { name: "finishing_notes", label: "Finishing Notes", type: "textarea" },
      { name: "carton_label_part_number", label: "Carton Label Part Number", type: "text", tab: "Carton Label" },
      { name: "carton_label_description_a", label: "Carton Label Description A", type: "text", tab: "Carton Label" },
      { name: "carton_label_description_b", label: "Carton Label Description B", type: "text", tab: "Carton Label" },
      { name: "carton_label_description_c", label: "Carton Label Description C", type: "text", tab: "Carton Label" },
      { name: "carton_label_finishing_1", label: "Carton Label Finishing 1", type: "text", tab: "Carton Label" },
      { name: "carton_label_finishing_2", label: "Carton Label Finishing 2", type: "text", tab: "Carton Label" },
      {
        name: "carton_label_is_unique",
        label: "Unique Carton Label",
        type: "checkbox",
        tab: "Carton Label",
        helpText: "Turn this on when the customer requires a special carton label format.",
      },
      {
        name: "carton_label_format",
        label: "Carton Label Format",
        type: "select",
        choices: choiceLists.cartonLabelFormat,
        defaultValue: "standard",
        tab: "Carton Label",
        showWhen: { carton_label_is_unique: true },
        clearWhenHidden: "standard",
        helpText: "The Labels tab will automatically use this format.",
      },
      { name: "job_notes", label: "Job Notes", type: "textarea" },
    ],
  },

  {
    key: "production-schedule",
    endpoint: "production-schedule",
    label: "Scheduling",
    singular: "Schedule Entry",
    group: "production",
    icon: Factory,
    accent: "#60a5fa",
    disableCreate: true,
    viewMode: "productionSchedule",
    defaultOrdering: "status,press__name,press_sequence,due_date,job_ticket__ticket_number",
    tagline: "Manage scheduled jobs by status, press assignment, ship date, and operator progress.",
    columns: [
      "order_number",
      "order_date",
      "due_date",
      "job_ticket_number",
      "customer_name",
      "job_name",
      "customer_po",
      "status",
      "press_name",
      "press_sequence",
      "operator",
      "priority",
      "quantity_to_ship",
      "quantity_to_stock",
      "scheduled_by",
    ],
    fields: [
      {
        name: "job_ticket",
        label: "Job Ticket",
        type: "searchRelation",
        relation: "job-tickets",
        required: true,
        searchable: true,
        maxResults: 250,
        searchFields: ["ticket_number", "customer_name", "job_name", "product_code", "material_spec_code", "material_spec_name", "material_spec_family", "recipe_name"],
      },
      {
        name: "customer",
        label: "Customer",
        type: "searchRelation",
        relation: "customers",
        searchable: true,
        lookupPageSize: 1000,
        lookupFetchAll: true,
        searchFields: ["name", "customer_code", "contact_name", "phone", "email"],
      },
      { name: "customer_po", label: "Customer PO", type: "text" },
      { name: "scheduled_by", label: "Scheduled By", type: "text" },
      { name: "last_updated_by", label: "Last Updated By", type: "text", hidden: true },
      { name: "status", label: "Status", type: "select", choices: choiceLists.productionScheduleStatus, defaultValue: "unscheduled" },
      { name: "priority", label: "Priority", type: "select", choices: choiceLists.jobTicketPriority, defaultValue: "normal" },
      { name: "quantity_to_ship", label: "Qty to Ship", type: "number", step: "0.001", defaultValue: 0 },
      { name: "quantity_to_stock", label: "Qty to Stock", type: "number", step: "0.001", defaultValue: 0 },
      { name: "order_date", label: "Date Scheduled", type: "date" },
      { name: "scheduled_date", label: "Scheduled Date", type: "date", hidden: true },
      { name: "due_date", label: "Ship Date", type: "date" },
      {
        name: "press",
        label: "Press",
        type: "searchRelation",
        relation: "presses",
        searchable: true,
        maxResults: 150,
        searchFields: ["name", "location_name", "location_full_path", "max_web_width_inches"],
      },
      { name: "press_sequence", label: "Press Order #", type: "number", step: "1" },
      { name: "operator", label: "Operator", type: "text" },
      { name: "actual_footage", label: "Actual Footage", type: "number", step: "0.01" },
      { name: "footage_report", label: "Footage Report", type: "textarea" },
      { name: "notes", label: "Operator Note", type: "textarea" },
    ],
  },

  {
    key: "customer-orders",
    endpoint: "customer-orders",
    label: "Customer Orders",
    singular: "Customer Order",
    group: "production",
    icon: History,
    accent: "#a78bfa",
    defaultOrdering: "-order_date,-scheduled_date,customer_name,job_name",
    disableCreate: true,
    disableMutate: true,
    tagline: "Permanent customer order pool created automatically from scheduled jobs.",
    columns: [
      "order_date",
      "scheduled_date",
      "due_date",
      "customer_name",
      "job_ticket_number",
      "job_name",
      "customer_po",
      "quantity_to_ship",
      "quantity_to_stock",
      "priority",
      "status",
      "press_name",
      "press_sequence",
      "operator",
      "scheduled_by",
    ],
    fields: [],
  },

  {
    key: "customer-order-events",
    endpoint: "customer-order-events",
    label: "History",
    singular: "Order Event",
    group: "production",
    icon: History,
    accent: "#94a3b8",
    defaultOrdering: "-created_at",
    disableCreate: true,
    disableMutate: true,
    tagline: "Automatic history of scheduling changes and customer order activity.",
    columns: [
      "created_at",
      "event_type",
      "order_customer_name",
      "job_ticket_number",
      "order_job_name",
      "performed_by",
      "summary",
    ],
    fields: [],
  },

  {
    key: "material-master-types",
    endpoint: "material-master-types",
    label: "Material Types",
    singular: "Material Type",
    group: "production-material",
    icon: Layers3,
    accent: "#0ea5e9",
    hideFromNav: true,
    defaultOrdering: "code,name",
    tagline: "Central material type list used to connect job tickets, material specs, inventory, and quoting.",
    columns: [
      "code",
      "name",
      "is_active",
      "description",
    ],
    fields: [
      { name: "code", label: "Type Code", type: "text", required: true, placeholder: "PM" },
      { name: "name", label: "Name", type: "text", required: true, placeholder: "Poly Matte" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },

  {
    key: "materials",
    endpoint: "materials",
    label: "All Material Options",
    singular: "Material Option",
    group: "production-material",
    icon: Layers3,
    accent: "#84cc16",
    hideFromNav: true,
    defaultOrdering: "material_type,company,name,code",
    tagline: "Master data types for finished raw materials, faces, liners, adhesives, silicone, and coatings. Inventory rolls link back to these records.",
    columns: [
      "material_type",
      "code",
      "master_type_code",
      "name",
      "company",
      "face_material_name",
      "liner_material_name",
      "adhesive_material_name",
      "liner_pounds",
      "gsm",
      "material_family",
      "is_active",
    ],
    fields: materialFields("coated_stock", false, "PM 40# finished raw material"),
  },

  ...materialTypeResources.map(({ key, label, singular, materialType, accent, placeholder }) => ({
    key,
    endpoint: "materials",
    filters: { material_type: materialType },
    label,
    singular,
    group: "production-material",
    icon: Layers3,
    accent,
    defaultOrdering: "company,name,code",
    tagline: materialType === "coated_stock"
      ? "Material records for coated constructions. Tri-State materials can be scheduled to the coater; outside materials stay reference-only."
      : `${label} reusable component list. Add supplier options to each data type, then inventory rolls can link back to the correct supplier and lot.`,
    columns: materialType === "coated_stock" ? finishedMaterialColumns : baseMaterialColumns,
    fields: materialFields(materialType, true, placeholder),
  })),

  {
    key: "material-supplier-options",
    endpoint: "material-supplier-options",
    label: "Material Supplier / Purchase Options",
    singular: "Material Supplier / Purchase Option",
    group: "production-material",
    icon: Store,
    accent: "#14b8a6",
    hideFromNav: true,
    defaultOrdering: "material__material_type,material__name,supplier_name,option_name",
    tagline: "Supplier/order options linked to a face, liner, adhesive, silicone, or coating data type.",
    columns: [
      "material_type",
      "material_name",
      "supplier_name",
      "option_name",
      "supplier_item_number",
      "thickness_mil",
      "width_inches",
      "length_feet",
      "is_active",
    ],
    fields: materialSupplierOptionFields(),
  },

  {
    key: "boxes",
    endpoint: "boxes",
    label: "Boxes",
    singular: "Box",
    group: "production-material",
    icon: PackageCheck,
    accent: "#fbbf24",
    defaultOrdering: "supplier,name,item_number",
    tagline: "Box master data: size, supplier, and item number used by job tickets.",
    columns: [
      "item_number",
      "name",
      "supplier",
      "width_inches",
      "length_inches",
      "height_inches",
      "is_active",
    ],
    fields: [
      { name: "name", label: "Box Name", type: "text", required: true, placeholder: "4 x 4 roll carton" },
      { name: "item_number", label: "Item #", type: "text" },
      { name: "supplier", label: "Supplier", type: "text" },
      { name: "width_inches", label: "Width", type: "number", step: "0.0001" },
      { name: "length_inches", label: "Length", type: "number", step: "0.0001" },
      { name: "height_inches", label: "Height", type: "number", step: "0.0001" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },

  {
    key: "box-inventory",
    endpoint: "box-inventory",
    label: "Box Inventory",
    singular: "Box Inventory",
    group: "inventory",
    icon: PackageCheck,
    accent: "#f59e0b",
    defaultOrdering: "box__name,lot_number",
    tagline: "Physical box inventory by lot, quantity, status, and location.",
    columns: [
      "box_item_number",
      "box_name",
      "box_supplier",
      "lot_number",
      "quantity",
      "status",
      "location_name",
      "received_date",
    ],
    fields: [
      {
        name: "box",
        label: "Box",
        type: "searchRelation",
        relation: "boxes",
        searchable: true,
        required: true,
        searchFields: ["name", "item_number", "supplier", "width_inches", "length_inches", "height_inches"],
      },
      { name: "lot_number", label: "Lot #", type: "text" },
      { name: "quantity", label: "Quantity", type: "number", step: "0.001", defaultValue: 0 },
      { name: "status", label: "Status", type: "select", choices: choiceLists.rawMaterialStatus, defaultValue: "available" },
      { name: "received_date", label: "Received", type: "date" },
      {
        name: "location",
        label: "Location",
        type: "searchRelation",
        relation: "locations",
        searchable: true,
        searchFields: ["name", "code", "location_type", "parent_name", "supplier_name"],
      },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },

  {
    key: "cores",
    endpoint: "cores",
    label: "Cores",
    singular: "Core",
    group: "production-material",
    icon: PackageMinus,
    accent: "#f97316",
    defaultOrdering: "supplier,core_size_inches,name,item_number",
    tagline: "Core master data used by job tickets and core inventory locations.",
    columns: [
      "item_number",
      "name",
      "supplier",
      "core_size_inches",
      "is_active",
    ],
    fields: [
      { name: "name", label: "Core Name", type: "text", required: true, placeholder: "3 inch core" },
      { name: "item_number", label: "Item #", type: "text" },
      { name: "supplier", label: "Supplier", type: "text" },
      { name: "core_size_inches", label: "Core Size", type: "number", step: "0.0001" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },

  {
    key: "core-inventory",
    endpoint: "core-inventory",
    label: "Core Inventory",
    singular: "Core Inventory",
    group: "inventory",
    icon: PackageMinus,
    accent: "#fb7185",
    defaultOrdering: "core__core_size_inches,core__name,lot_number",
    tagline: "Physical core inventory by core, location, quantity, and status.",
    columns: [
      "core_item_number",
      "core_name",
      "core_size_inches",
      "lot_number",
      "quantity",
      "status",
      "location_name",
      "received_date",
    ],
    fields: [
      {
        name: "core",
        label: "Core",
        type: "searchRelation",
        relation: "cores",
        searchable: true,
        required: true,
        searchFields: ["name", "item_number", "supplier", "core_size_inches"],
      },
      { name: "lot_number", label: "Lot #", type: "text" },
      { name: "quantity", label: "Quantity", type: "number", step: "0.001", defaultValue: 0 },
      { name: "status", label: "Status", type: "select", choices: choiceLists.rawMaterialStatus, defaultValue: "available" },
      { name: "received_date", label: "Received", type: "date" },
      {
        name: "location",
        label: "Location",
        type: "searchRelation",
        relation: "locations",
        searchable: true,
        searchFields: ["name", "code", "location_type", "parent_name", "supplier_name"],
      },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },

  {
    key: "packaging-inventory",
    endpoint: "box-inventory",
    label: "Packaging Inventory",
    singular: "Packaging Inventory",
    group: "inventory",
    icon: PackageCheck,
    accent: "#f97316",
    defaultOrdering: "box__name,lot_number",
    viewMode: "packagingInventory",
    disableCreate: true,
    tagline: "Combined box and core inventory by location, quantity, status, and item number.",
    columns: [],
    fields: [],
  },

  {
    key: "raw-materials",
    endpoint: "raw-materials",
    label: "Material Inventory",
    singular: "Inventory Roll",
    group: "inventory",
    icon: Layers3,
    accent: "#22c55e",
    defaultOrdering: "-serial_number",
    pageSize: 1000,
    fetchAll: true,
    tagline: "Physical material inventory by material, lot, width, length, and location.",
    viewMode: "materialInventory",
    columns: [
      "serial_number",
      "material_code",
      "material_name",
      "material_master_type_code",
      "material_family",
      "lot_number",
      "width_inches",
      "length_feet",
      "quantity",
      "status",
      "location_name",
    ],
    fields: [
      {
        name: "material",
        label: "Finished Material / Family",
        type: "searchRelation",
        relation: "materials",
        searchable: true,
        maxResults: 250,
        required: true,
        lookupFilters: { material_type: "coated_stock" },
        searchFields: ["material_master_type_code", "material_master_type_name", "material_family", "name", "code", "company", "gsm", "notes"],
      },
      { name: "lot_number", label: "Lot #", type: "text" },
      { name: "width_inches", label: "Width", type: "number", step: "0.0001" },
      { name: "length_feet", label: "Length / Feet", type: "number", step: "0.01" },
      { name: "status", label: "Status", type: "select", choices: choiceLists.rawMaterialStatus, defaultValue: "available" },
      {
        name: "location",
        label: "Location",
        type: "searchRelation",
        relation: "locations",
        searchable: true,
        searchFields: ["name", "code", "location_type", "parent_name", "supplier_name"],
      },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },

  {
    key: "material-usages",
    endpoint: "material-usages",
    label: "Material Usage",
    singular: "Usage Record",
    group: "inventory",
    icon: PackageMinus,
    accent: "#f97316",
    defaultOrdering: "-used_date,-created_at",
    tagline: "Permanent ledger of material consumed from inventory by coater, finishing, scrap, or manual adjustments.",
    columns: [
      "used_date",
      "usage_type",
      "reference",
      "material_code",
      "material_name",
      "inventory_serial",
      "inventory_lot",
      "quantity",
      "unit",
      "used_by",
    ],
    fields: [
      {
        name: "inventory",
        label: "Inventory",
        type: "searchRelation",
        relation: "raw-materials",
        searchable: true,
        required: true,
        maxResults: 250,
        searchFields: ["material_name", "material_code", "name", "serial_number", "lot_number", "material_type", "location_name"],
      },
      {
        name: "material",
        label: "Material",
        type: "searchRelation",
        relation: "materials",
        searchable: true,
        searchFields: ["name", "code", "company", "material_type", "material_family"],
      },
      { name: "usage_type", label: "Usage Type", type: "select", choices: choiceLists.materialUsageType, defaultValue: "manual" },
      { name: "quantity", label: "Quantity Used", type: "number", step: "0.001", defaultValue: 0 },
      { name: "unit", label: "Unit", type: "select", choices: choiceLists.rawMaterialUnit, defaultValue: "lf" },
      { name: "used_date", label: "Used Date", type: "date", defaultValue: new Date().toISOString().slice(0, 10) },
      { name: "used_by", label: "Used By", type: "text" },
      { name: "reference", label: "Reference", type: "text", placeholder: "Job, tag, reason, or coordinator note" },
      {
        name: "coater_roll_tag",
        label: "Coater Roll Tag",
        type: "searchRelation",
        relation: "coater-roll-tags",
        searchable: true,
        searchFields: ["tag_number", "name", "result_serial_number", "operator"],
      },
      {
        name: "finished_inventory",
        label: "Finished Inventory",
        type: "searchRelation",
        relation: "finished-inventory",
        searchable: true,
        searchFields: ["name", "sku", "job_ticket_number", "material_inventory_serial"],
      },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },

  {
    key: "coater-roll-tags",
    endpoint: "coater-roll-tags",
    label: "Coater Roll Tags",
    singular: "Coater Roll Tag",
    group: "production",
    icon: Ruler,
    accent: "#fb7185",
    defaultOrdering: "-run_date,tag_number",
    tagline: "Operator coater workflow: select liner, face, adhesive, silicone, coating, print a roll tag, and log the produced roll into inventory.",
    columns: [
      "tag_number",
      "name",
      "status",
      "print_status",
      "liner_code",
      "face_code",
      "adhesive_code",
      "silicone_code",
      "result_serial_number",
      "width_inches",
      "length_feet",
      "press_name",
      "operator",
      "run_date",
    ],
    fields: [
      { name: "tag_number", label: "Roll Tag #", type: "text", required: true, placeholder: "CRT-1001" },
      { name: "name", label: "Roll Name", type: "text", required: true, placeholder: "Kruger 40# / PolyMatte coated stock" },
      { name: "status", label: "Status", type: "select", choices: choiceLists.coaterStatus, defaultValue: "scheduled" },
      { name: "print_status", label: "Print Status", type: "select", choices: choiceLists.printStatus, defaultValue: "not_printed" },
      { name: "scheduled_by", label: "Scheduled By", type: "text" },
      { name: "cut_description", label: "Cut Description", type: "text" },
      { name: "operator_notes", label: "Operator Note", type: "textarea" },
      {
        name: "scheduled_material",
        label: "Scheduled Material",
        type: "searchRelation",
        relation: "materials",
        searchable: true,
        searchFields: ["name", "code", "company", "material_type"],
      },
      {
        name: "liner",
        label: "Liner",
        type: "searchRelation",
        relation: "materials",
        lookupFilters: { material_type: "liner" },
        required: true,
        searchable: true,
        searchFields: ["name", "code", "company", "material_type", "material_family", "liner_pounds", "gsm"],
      },
      {
        name: "liner_inventory",
        label: "Liner Inventory",
        type: "searchRelation",
        relation: "raw-materials",
        lookupFilters: { material_type: "liner" },
        searchable: true,
        searchFields: ["material_name", "material_code", "name", "serial_number", "lot_number", "width_inches", "location_name"],
      },
      {
        name: "face",
        label: "Face",
        type: "searchRelation",
        relation: "materials",
        lookupFilters: { material_type: "face" },
        required: true,
        searchable: true,
        searchFields: ["name", "code", "company", "material_type", "material_family", "gsm"],
      },
      {
        name: "face_inventory",
        label: "Face Inventory",
        type: "searchRelation",
        relation: "raw-materials",
        lookupFilters: { material_type: "face" },
        searchable: true,
        searchFields: ["material_name", "material_code", "name", "serial_number", "lot_number", "width_inches", "location_name"],
      },
      {
        name: "adhesive",
        label: "Adhesive",
        type: "searchRelation",
        relation: "materials",
        lookupFilters: { material_type: "adhesive" },
        required: true,
        searchable: true,
        searchFields: ["name", "code", "company", "material_type", "material_family", "gsm"],
      },
      {
        name: "adhesive_inventory",
        label: "Adhesive Inventory",
        type: "searchRelation",
        relation: "raw-materials",
        lookupFilters: { material_type: "adhesive" },
        searchable: true,
        searchFields: ["material_name", "material_code", "name", "serial_number", "lot_number", "location_name"],
      },
      {
        name: "silicone",
        label: "Silicone",
        type: "searchRelation",
        relation: "materials",
        lookupFilters: { material_type: "silicone" },
        required: true,
        searchable: true,
        searchFields: ["name", "code", "company", "material_type", "material_family", "gsm"],
      },
      {
        name: "silicone_inventory",
        label: "Silicone Inventory",
        type: "searchRelation",
        relation: "raw-materials",
        lookupFilters: { material_type: "silicone" },
        searchable: true,
        searchFields: ["material_name", "material_code", "name", "serial_number", "lot_number", "location_name"],
      },
      {
        name: "coating",
        label: "Coating",
        type: "searchRelation",
        relation: "materials",
        lookupFilters: { material_type: "coating" },
        searchable: true,
        searchFields: ["name", "code", "company", "material_type", "material_family", "gsm"],
      },
      {
        name: "coating_inventory",
        label: "Coating Inventory",
        type: "searchRelation",
        relation: "raw-materials",
        lookupFilters: { material_type: "coating" },
        searchable: true,
        searchFields: ["material_name", "material_code", "name", "serial_number", "lot_number", "location_name"],
      },
      {
        name: "produced_material",
        label: "Produced Material",
        type: "searchRelation",
        relation: "materials",
        lookupFilters: { material_type: "coated_stock" },
        searchable: true,
        searchFields: ["name", "code", "company", "material_type"],
      },
      { name: "result_code", label: "Result Code", type: "text" },
      { name: "result_serial_number", label: "Result Serial #", type: "text" },
      { name: "result_lot_number", label: "Result Lot #", type: "text" },
      { name: "width_inches", label: "Width", type: "number", step: "0.0001" },
      { name: "length_feet", label: "Length", type: "number", step: "0.01" },
      { name: "weight_lbs", label: "Weight", type: "number", step: "0.01" },
      { name: "operator", label: "Operator", type: "text" },
      { name: "run_date", label: "Run Date", type: "date" },
      {
        name: "press",
        label: "Press",
        type: "searchRelation",
        relation: "presses",
        searchable: true,
        searchFields: ["name", "location_name", "location_full_path"],
      },
      {
        name: "location",
        label: "Inventory Location",
        type: "searchRelation",
        relation: "locations",
        searchable: true,
        searchFields: ["name", "code", "location_type", "parent_name"],
      },
      { name: "log_inventory", label: "Log to Inventory", type: "checkbox", defaultValue: true },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },

  {
    key: "finished-inventory",
    endpoint: "finished-inventory",
    label: "Finished Inventory",
    singular: "Finished Item",
    group: "inventory",
    icon: PackageCheck,
    accent: "#fbbf24",
    defaultOrdering: "-run_date,name",
    pageSize: 1000,
    fetchAll: true,
    viewMode: "finishedInventory",
    tagline: "Finished rolls or cases with material dimensions, serials, run crew, and status.",
    columns: [
      "name",
      "sku",
      "job_ticket_number",
      "imported_tsm_id",
      "quantity",
      "unit",
      "location_name",
      "location_full_path",
      "status",
      "face_type",
      "liner_type",
      "run_date",
    ],
    fields: [
      { name: "name", label: "Item Name", type: "text", required: true, placeholder: "4 x 4 PMDT finished roll" },
      { name: "sku", label: "SKU", type: "text" },
      {
        name: "job_ticket",
        label: "Job Ticket",
        type: "searchRelation",
        relation: "job-tickets",
        searchable: true,
        searchFields: ["ticket_number", "customer_name", "job_name", "product_code", "status"],
      },
      {
        name: "material_inventory",
        label: "Material Roll",
        type: "searchRelation",
        relation: "raw-materials",
        searchable: true,
        lookupFilters: { material_type: "coated_stock" },
        searchFields: ["name", "code", "serial_number", "lot_number", "material_type"],
      },
      {
        name: "recipe",
        label: "Label Layout",
        type: "searchRelation",
        relation: "recipes",
        searchable: true,
        searchFields: ["name", "label_width_inches", "label_length_inches", "face_type", "liner_type"],
      },
      {
        name: "recipe_option",
        label: "Tooling Option",
        type: "searchRelation",
        relation: "recipe-options",
        searchable: true,
        searchFields: ["name", "recipe_name", "press_name", "setup_type"],
      },
      { name: "material_width_inches", label: "Material Width", type: "number", step: "0.0001" },
      { name: "material_length_feet", label: "Material Length", type: "number", step: "0.01" },
      { name: "face_type", label: "Face Type", type: "select", choices: choiceLists.faceType },
      { ...linerDataTypeField, label: "Liner Type" },
      { name: "liner_serial_number", label: "Liner Serial #", type: "text" },
      { name: "face_serial_number", label: "Face Serial #", type: "text" },
      { name: "quantity", label: "Quantity", type: "number", step: "0.001", defaultValue: 0 },
      { name: "unit", label: "Unit", type: "select", choices: choiceLists.finishedInventoryUnit, defaultValue: "roll" },
      { name: "status", label: "Status", type: "select", choices: choiceLists.finishedInventoryStatus, defaultValue: "available" },
      { name: "operator", label: "Operator Who Ran", type: "text" },
      { name: "suboperator", label: "Suboperator Who Ran", type: "text" },
      { name: "run_date", label: "Run Date", type: "date" },
      {
        name: "location",
        label: "Location",
        type: "searchRelation",
        relation: "locations",
        searchable: true,
        searchFields: ["name", "code", "location_type", "parent_name"],
      },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },

  {
    key: "recipe-options",
    endpoint: "recipe-options",
    label: "Press Setup Options",
    singular: "Press Setup Option",
    group: "tooling",
    icon: PackageCheck,
    accent: "#7dd3fc",
    defaultOrdering: "recipe__name,press__name,-is_preferred,name",
    tagline: "Approved ways to run a label layout on each press.",
    columns: [
      "name",
      "recipe_name",
      "press_name",
      "setup_type",
      "estimated_setup_minutes",
      "is_preferred",
      "is_approved",
      "can_run",
    ],
    detail: "recipeOption",
    fields: [
      {
        name: "recipe",
        label: "Label Layout",
        type: "searchRelation",
        relation: "recipes",
        required: true,
        searchable: true,
        maxResults: 150,
        searchFields: [
          "name",
          "label_width_inches",
          "label_length_inches",
          "repeat_inches",
          "web_width_inches",
          "face_type",
          "liner_type",
          "shape_type",
          "cutting_type",
        ],
      },
      {
        name: "press",
        label: "Press",
        type: "searchRelation",
        relation: "presses",
        required: true,
        searchable: true,
        maxResults: 150,
        searchFields: [
          "name",
          "location_name",
          "location_full_path",
          "color_count",
          "die_station_count",
          "max_web_width_inches",
        ],
      },
      {
        name: "name",
        label: "Setup Name",
        type: "text",
        placeholder: "Auto: Label Layout - Press Name",
        helpText: "Leave blank and the system will build this from the label layout and selected press.",
      },
      {
        name: "setup_type",
        label: "Setup Type",
        type: "select",
        choices: choiceLists.setupType,
        defaultValue: "standard",
      },
      {
        name: "estimated_setup_minutes",
        label: "Setup Min",
        type: "number",
      },
      {
        name: "is_preferred",
        label: "Preferred",
        type: "checkbox",
      },
      {
        name: "is_approved",
        label: "Approved",
        type: "checkbox",
        defaultValue: true,
      },
      {
        name: "is_active",
        label: "Active",
        type: "checkbox",
        defaultValue: true,
      },
      {
        name: "requires_undercut",
        label: "Undercut",
        type: "checkbox",
      },
      {
        name: "requires_manual_review",
        label: "Manual Review",
        type: "checkbox",
      },
      {
        name: "setup_notes",
        label: "Setup Notes",
        type: "textarea",
      },
      {
        name: "operator_notes",
        label: "Operator Notes",
        type: "textarea",
      },
    ],
  },

  {
    key: "recipes",
    endpoint: "recipes",
    label: "Label Layouts",
    singular: "Label Layout",
    group: "tooling",
    icon: Shapes,
    accent: "#c084fc",
    defaultOrdering: "name",
    tagline: "Reusable face, liner, cut, size, and perf layout definitions.",
    columns: [
      "name",
      "label_width_inches",
      "label_length_inches",
      "repeat_inches",
      "web_width_inches",
      "shape_type",
      "cutting_type",
      "perf_option",
      "internal_perf_option",
      "face_type",
      "liner_type",
    ],
    fields: [
      {
        name: "name",
        label: "Name of Design",
        type: "text",
        required: true,
        placeholder: "2 x 1 Poly NP",
      },

      { name: "label_width_inches", label: "Label Width", type: "number", step: "0.0001" },
      { name: "label_length_inches", label: "Label Length", type: "number", step: "0.0001" },
      { name: "repeat_inches", label: "Label Repeat", type: "number", step: "0.0001" },

      {
        name: "shape_type",
        label: "Label Shape",
        type: "select",
        choices: choiceLists.layoutShapeType,
        defaultValue: "rcr",
      },
      {
        name: "cutting_type",
        label: "Label Cut",
        type: "select",
        choices: choiceLists.labelCutType,
        defaultValue: "to_liner",
      },
      {
        name: "face_type",
        label: "Face Type",
        type: "select",
        choices: choiceLists.faceType,
        lookupRelation: "material-faces",
        lookupValueField: "name",
        lookupLabelFields: ["name", "code", "material_family"],
      },
      { ...linerDataTypeField, label: "Liner Type" },
      {
        name: "perf_option",
        label: "Between Labels",
        type: "select",
        choices: choiceLists.perfOption,
        defaultValue: "none",
      },
      {
        name: "tpi",
        label: "Perf TPI",
        type: "number",
        step: "0.0001",
        showWhen: { perf_option: "perf" },
        clearWhenHidden: null,
      },
      {
        name: "perf_notes",
        label: "Between-label Notes",
        type: "textarea",
        showWhen: { perf_option: ["perf", "sheeted"] },
        clearWhenHidden: "",
      },
      {
        name: "internal_perf_option",
        label: "Internal Perf",
        type: "select",
        choices: choiceLists.perfOption,
        defaultValue: "none",
      },
      {
        name: "internal_perf_cutting_type",
        label: "Internal Perf Cut",
        type: "select",
        choices: choiceLists.internalPerfCuttingType,
        showWhen: { internal_perf_option: "perf" },
        clearWhenHidden: "",
      },
      {
        name: "internal_perf_tpi",
        label: "Internal Perf TPI",
        type: "number",
        step: "0.0001",
        showWhen: { internal_perf_option: "perf" },
        clearWhenHidden: null,
      },
      {
        name: "internal_perf_notes",
        label: "Internal Perf Notes",
        type: "textarea",
        showWhen: { internal_perf_option: "perf" },
        clearWhenHidden: "",
      },
      {
        name: "is_active",
        label: "Active",
        type: "checkbox",
        defaultValue: true,
      },
      {
        name: "notes",
        label: "Recipe Notes",
        type: "textarea",
      },
    ],
  },

  {
    key: "print-plates",
    endpoint: "print-plates",
    label: "Print Plates",
    singular: "Print Plate",
    group: "tooling",
    icon: Printer,
    accent: "#38bdf8",
    defaultOrdering: "recipe__name,plate_number",
    tagline: "Print plates linked to label layouts, with stations for each color.",
    columns: [
      "recipe_name",
      "plate_number",
      "customer_plate_number",
      "serial_number",
      "description",
      "number_across",
      "number_around",
      "station_count",
      "is_active",
    ],
    fields: [
      {
        name: "recipe",
        label: "Label Layout",
        type: "searchRelation",
        relation: "recipes",
        required: true,
        searchable: true,
        maxResults: 150,
        searchFields: ["name", "face_type", "liner_type", "label_width_inches", "label_length_inches", "repeat_inches"],
      },
      { name: "plate_number", label: "Print Plate #", type: "text", required: true },
      { name: "customer_plate_number", label: "Customer Plate #", type: "text" },
      { name: "serial_number", label: "Serial #", type: "text" },
      { name: "description", label: "Description", type: "text" },
      { name: "number_across", label: "Number Across", type: "number" },
      { name: "number_around", label: "Number Around", type: "number" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },

  {
    key: "print-stations",
    endpoint: "print-stations",
    label: "Print Stations",
    singular: "Print Station",
    group: "tooling",
    icon: Printer,
    accent: "#0ea5e9",
    defaultOrdering: "print_plate__recipe__name,print_plate__plate_number,station_number",
    tagline: "Color stations for print plates.",
    columns: [
      "recipe_name",
      "print_plate_number",
      "station_number",
      "station_plate_number",
      "print_cylinder_tooth_count",
      "anilox_gear_number",
      "pms_color",
      "color_type",
      "is_active",
    ],
    fields: [
      {
        name: "print_plate",
        label: "Print Plate",
        type: "searchRelation",
        relation: "print-plates",
        required: true,
        searchable: true,
        maxResults: 200,
        searchFields: ["plate_number", "customer_plate_number", "serial_number", "recipe_name", "description"],
      },
      { name: "station_number", label: "Station #", type: "number", defaultValue: 1 },
      { name: "station_plate_number", label: "Station Plate #", type: "text" },
      { name: "print_cylinder_tooth_count", label: "Print Cylinder Tooth", type: "number" },
      { name: "anilox_gear_number", label: "Anilox Gear #", type: "text" },
      { name: "pms_color", label: "PMS Color", type: "text" },
      { name: "color_type", label: "Color Type", type: "select", choices: choiceLists.printColorType, defaultValue: "spot" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },

  {
    key: "recipe-tools",
    endpoint: "recipe-tools",
    label: "Tool Assignments",
    singular: "Tool Assignment",
    group: "tooling",
    icon: Wrench,
    accent: "#fbbf24",
    defaultOrdering: "recipe_option__recipe__name,recipe_option__press__name,recipe_option__name,tool_role,station_number,tool_type",
    tagline: "Assign exact dies, mags, perf tooling, and manual tools to each press setup option.",
    columns: [
      "recipe_name",
      "press_name",
      "recipe_option_name",
      "tool_role",
      "tool_type",
      "station_number",
      "tool_name",
      "is_required",
    ],
    fields: [
      {
        name: "recipe_option",
        label: "Press Setup Option",
        type: "searchRelation",
        relation: "recipe-options",
        required: true,
        searchable: true,
        maxResults: 200,
        searchFields: [
          "name",
          "recipe_name",
          "press_name",
          "setup_type",
          "tool_summary",
          "can_run",
        ],
        helpText: "Choose the approved option this tool belongs to.",
      },

      {
        name: "tool_role",
        label: "Tool Role",
        type: "select",
        choices: choiceLists.toolRole,
        defaultValue: "top",
        required: true,
        helpText: "Top/Main = normal die + mag. Undercut = second die + mag. Perf = external perf tooling.",
      },

      {
        name: "tool_type",
        label: "Tool Type",
        type: "select",
        choices: choiceLists.toolType,
        defaultValue: "flex_die",
        required: true,
        helpText: "Pick Mag to open the searchable mag selector.",
      },

      {
        name: "station_number",
        label: "Station",
        type: "number",
        helpText: "Optional. Use this for press station order.",
      },

      {
        name: "flex_die",
        label: "Flex Die",
        type: "searchRelation",
        relation: "flex-dies",
        searchable: true,
        maxResults: 200,
        showWhen: { tool_type: "flex_die" },
        clearWhenHidden: null,
        searchFields: [
          "name",
          "original_serial_number",
          "serial_numbers",
          "gear",
          "number_across",
          "number_around",
          "gap_across_inches",
          "label_width_inches",
          "label_length_inches",
          "repeat_inches",
          "web_width_inches",
          "active_die_count",
          "target_die_count",
          "shape_type",
          "cutting_type",
          "face_type",
          "liner_type",
          "status",
          "supplier_name",
          "current_location_name",
          "current_location_full_path",
        ],
        helpText: "Search by die jacket, serial, gear, size, across/around, face, liner, or location.",
      },

      {
        name: "mag",
        label: "Mag",
        type: "searchRelation",
        relation: "mags",
        searchable: true,
        maxResults: 300,
        showWhen: { tool_type: "mag" },
        clearWhenHidden: null,
        searchFields: [
          "name",
          "tooth_count",
          "repeat_inches",
          "face_width_inches",
          "status",
          "supplier_name",
          "current_location_name",
          "current_location_full_path",
          "compatible_presses",
          "compatible_press_names",
          "press_name",
        ],
        helpText: "Search by tooth count, mag name, repeat, face width, status, location, or compatible press.",
      },

      {
        name: "perf_cylinder",
        label: "Perf Cylinder",
        type: "searchRelation",
        relation: "perf-cylinders",
        searchable: true,
        maxResults: 200,
        showWhen: { tool_type: "perf_cylinder" },
        clearWhenHidden: null,
        searchFields: [
          "name",
          "gear_tooth_count",
          "cylinder_width_inches",
          "max_blade_count",
          "status",
          "supplier_name",
          "current_location_name",
          "current_location_full_path",
          "compatible_presses",
          "compatible_press_names",
        ],
        helpText: "Use this for external perf tooling.",
      },

      {
        name: "perf_blade_setup",
        label: "Blade Setup",
        type: "searchRelation",
        relation: "perf-blade-setups",
        searchable: true,
        maxResults: 200,
        showWhen: { tool_type: "perf_blade_setup" },
        clearWhenHidden: null,
        searchFields: [
          "name",
          "perf_cylinder_name",
          "blade_count",
          "standard_repeat_inches",
          "has_offset_blades",
          "is_active",
        ],
        helpText: "Use this when the perf setup is based on blades inside a perf cylinder.",
      },

      {
        name: "manual_description",
        label: "Manual Tool",
        type: "text",
        showWhen: { tool_type: ["manual_tooling", "other"] },
        clearWhenHidden: "",
        placeholder: "Example: Special hand setup / operator note",
      },

      {
        name: "is_required",
        label: "Required",
        type: "checkbox",
        defaultValue: true,
        helpText: "Required tooling affects whether the option can run.",
      },

      {
        name: "notes",
        label: "Notes",
        type: "textarea",
      },
    ],
  },

  {
    key: "flex-dies",
    endpoint: "flex-dies",
    label: "Flex Dies",
    singular: "Flex Die",
    group: "tooling",
    icon: Scissors,
    accent: "#34d399",
    defaultOrdering: "label_width_inches,label_length_inches,gear,name",
    tagline: "Die jackets by size, gap, count, serial history, and reorder status.",
    columns: [
      "name",
      "original_serial_number",
      "label_width_inches",
      "label_length_inches",
      "number_across",
      "number_around",
      "gap_across_inches",
      "web_width_inches",
      "active_die_count",
      "target_die_count",
      "die_count_status",
      "face_type",
      "liner_type",
      "gear",
      "status",
      "current_location_name",
    ],
    searchMode: "flexDie",
    fields: [
      {
        name: "name",
        label: "Die Jacket / Tool #",
        type: "text",
        required: true,
        placeholder: "FD-13-1-1",
        section: "Die Jacket",
        sectionHint: "Use the jacket/tool folder number as the name.",
      },
      {
        name: "original_serial_number",
        label: "Original Serial #",
        type: "text",
      },
      {
        name: "dieline_image",
        label: "Dieline Image",
        type: "imageUpload",
        imageSlot: "dieline",
      },

      {
        name: "label_width_inches",
        label: "Label Width",
        type: "number",
        step: "0.0001",
        section: "Label Size",
        sectionHint: "Core die dimensions. Web width is calculated later from width, gap, and across.",
      },
      {
        name: "label_length_inches",
        label: "Label Length",
        type: "number",
        step: "0.0001",
      },
      {
        name: "repeat_inches",
        label: "Repeat",
        type: "number",
        step: "0.0001",
      },

      {
        name: "gap_across_inches",
        label: "Gap Across",
        type: "number",
        step: "0.0001",
        section: "Layout",
        sectionHint: "Gap is the space between labels. Auto web = width x across + gap x spaces between labels.",
      },
      {
        name: "gap_around_inches",
        label: "Gap Around",
        type: "number",
        step: "0.0001",
      },

      {
        name: "gear",
        label: "Gear/Tooth",
        type: "number",
      },
      {
        name: "number_across",
        label: "Across",
        type: "number",
      },
      {
        name: "number_around",
        label: "Around",
        type: "number",
      },
      {
        name: "manual_web_width",
        label: "Manual Web Width",
        type: "checkbox",
        helpText: "Leave off to calculate web width from width, gap, and across.",
      },
      {
        name: "web_width_inches",
        label: "Manual Web Width",
        type: "number",
        step: "0.0001",
        showWhen: { manual_web_width: true },
        clearWhenHidden: null,
      },
      {
        name: "active_die_count",
        label: "Active Dies In Jacket",
        type: "number",
        defaultValue: 1,
        section: "Die Count",
        sectionHint: "This folder may hold multiple physical dies with the same specs.",
      },
      {
        name: "target_die_count",
        label: "Target Dies",
        type: "number",
        defaultValue: 1,
      },
      {
        name: "serial_numbers",
        label: "Serial Numbers",
        type: "textarea",
        placeholder: "One serial number per line",
      },
      {
        name: "shape_type",
        label: "Shape",
        type: "select",
        choices: choiceLists.shapeType,
        section: "Material + Cut",
      },
      {
        name: "cutting_type",
        label: "Cutting",
        type: "select",
        choices: choiceLists.cuttingType,
      },
      {
        name: "face_type",
        label: "Face",
        type: "select",
        choices: choiceLists.faceType,
      },
      { ...linerDataTypeField },
      supplierField("tooling", { section: "Storage" }),
      {
        name: "current_location",
        label: "Location",
        type: "searchRelation",
        relation: "locations",
        searchable: true,
        searchFields: [
          "name",
          "code",
          "location_type",
          "parent_name",
          "supplier_name",
        ],
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        choices: choiceLists.toolStatus,
        defaultValue: "in_stock",
      },
    ],
  },

  {
    key: "mags",
    endpoint: "mags",
    label: "Mags",
    singular: "Mag",
    group: "tooling",
    icon: Gauge,
    accent: "#60a5fa",
    defaultOrdering: "tooth_count,name",
    tagline: "Mag cylinders by tooth count, repeat, face width, location, and press compatibility.",
    columns: [
      "name",
      "tooth_count",
      "repeat_inches",
      "face_width_inches",
      "status",
      "current_location_name",
    ],
    fields: [
      {
        name: "name",
        label: "Name",
        type: "text",
        required: true,
        placeholder: "MC-13-81",
      },
      {
        name: "tooth_count",
        label: "Tooth",
        type: "number",
      },
      {
        name: "repeat_inches",
        label: "Repeat",
        type: "number",
        step: "0.0001",
      },
      {
        name: "face_width_inches",
        label: "Face Width",
        type: "number",
        step: "0.0001",
      },
      supplierField("tooling"),
      {
        name: "current_location",
        label: "Location",
        type: "searchRelation",
        relation: "locations",
        searchable: true,
        searchFields: [
          "name",
          "code",
          "location_type",
          "parent_name",
          "supplier_name",
        ],
      },
      {
        name: "compatible_presses",
        label: "Compatible Presses",
        type: "multiRelation",
        relation: "presses",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        choices: choiceLists.toolStatus,
        defaultValue: "in_stock",
      },
      {
        name: "notes",
        label: "Notes",
        type: "textarea",
      },
    ],
  },

  {
    key: "perf-cylinders",
    endpoint: "perf-cylinders",
    label: "Perf Cylinders",
    singular: "Perf Cylinder",
    group: "tooling",
    icon: Ruler,
    accent: "#fb7185",
    defaultOrdering: "gear_tooth_count,name",
    tagline: "Perf cylinders by gear tooth count, width, max blade count, and location.",
    columns: [
      "name",
      "gear_tooth_count",
      "cylinder_width_inches",
      "max_blade_count",
      "status",
      "current_location_name",
    ],
    fields: [
      {
        name: "name",
        label: "Name",
        type: "text",
        required: true,
      },
      {
        name: "gear_tooth_count",
        label: "Gear Tooth",
        type: "number",
      },
      {
        name: "cylinder_width_inches",
        label: "Width",
        type: "number",
        step: "0.0001",
      },
      {
        name: "max_blade_count",
        label: "Max Blades",
        type: "number",
      },
      supplierField("tooling"),
      {
        name: "current_location",
        label: "Location",
        type: "searchRelation",
        relation: "locations",
        searchable: true,
        searchFields: [
          "name",
          "code",
          "location_type",
          "parent_name",
          "supplier_name",
        ],
      },
      {
        name: "compatible_presses",
        label: "Compatible Presses",
        type: "multiRelation",
        relation: "presses",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        choices: choiceLists.toolStatus,
        defaultValue: "in_stock",
      },
      {
        name: "notes",
        label: "Notes",
        type: "textarea",
      },
    ],
  },

  {
    key: "perf-blade-setups",
    endpoint: "perf-blade-setups",
    label: "Perf Blade Setups",
    singular: "Blade Setup",
    group: "tooling",
    icon: Settings2,
    accent: "#f97316",
    defaultOrdering: "perf_cylinder__name,name",
    tagline: "Blade setup recipes for perf cylinders.",
    columns: [
      "name",
      "perf_cylinder_name",
      "blade_types",
      "blade_count",
      "active_blade_count",
      "standard_repeat_inches",
      "has_sheeter_blade",
      "has_offset_blades",
      "is_active",
    ],
    fields: [
      {
        name: "perf_cylinder",
        label: "Perf Cylinder",
        type: "searchRelation",
        relation: "perf-cylinders",
        required: true,
        searchable: true,
        searchFields: [
          "name",
          "gear_tooth_count",
          "cylinder_width_inches",
          "status",
          "current_location_name",
          "current_location_full_path",
        ],
      },
      {
        name: "name",
        label: "Name",
        type: "text",
        required: true,
      },
      {
        name: "blade_count",
        label: "Blades",
        type: "number",
      },
      {
        name: "standard_repeat_inches",
        label: "Repeat",
        type: "number",
        step: "0.0001",
      },
      {
        name: "has_offset_blades",
        label: "Offset Blades",
        type: "checkbox",
      },
      {
        name: "is_active",
        label: "Active",
        type: "checkbox",
        defaultValue: true,
      },
      {
        name: "notes",
        label: "Notes",
        type: "textarea",
      },
    ],
  },

  {
    key: "perf-blades",
    endpoint: "perf-blades",
    label: "Perf Blades",
    singular: "Perf Blade",
    group: "tooling",
    icon: Layers3,
    accent: "#a3e635",
    defaultOrdering: "setup__name,blade_number",
    tagline: "Individual blades assigned to blade setups.",
    columns: [
      "setup_name",
      "perf_cylinder_name",
      "blade_number",
      "blade_type",
      "position_inches",
      "offset_inches",
      "is_active",
    ],
    fields: [
      {
        name: "setup",
        label: "Setup",
        type: "searchRelation",
        relation: "perf-blade-setups",
        required: true,
        searchable: true,
        searchFields: [
          "name",
          "perf_cylinder_name",
          "blade_count",
          "standard_repeat_inches",
        ],
      },
      {
        name: "blade_number",
        label: "Blade #",
        type: "number",
      },
      {
        name: "blade_type",
        label: "Blade Type",
        type: "select",
        choices: choiceLists.bladeType,
        defaultValue: "standard",
      },
      {
        name: "position_inches",
        label: "Position",
        type: "number",
        step: "0.0001",
      },
      {
        name: "offset_inches",
        label: "Offset",
        type: "number",
        step: "0.0001",
      },
      {
        name: "is_active",
        label: "Active",
        type: "checkbox",
        defaultValue: true,
      },
      {
        name: "notes",
        label: "Notes",
        type: "textarea",
      },
    ],
  },

  {
    key: "presses",
    endpoint: "presses",
    label: "Presses",
    singular: "Press",
    group: "plant",
    icon: Factory,
    accent: "#38bdf8",
    defaultOrdering: "name",
    tagline: "Press capability: location, colors, web width, die stations, and undercut capability.",
    columns: [
      "name",
      "location_name",
      "color_count",
      "die_station_count",
      "max_web_width_inches",
      "printer_ip",
      "printer_speed",
      "printer_darkness",
      "has_digital_print",
      "has_undercut_capability",
      "has_perf_capability",
      "is_active",
    ],
    fields: [
      {
        name: "name",
        label: "Name",
        type: "text",
        required: true,
      },
      {
        name: "location",
        label: "Location",
        type: "searchRelation",
        relation: "locations",
        searchable: true,
        searchFields: [
          "name",
          "code",
          "location_type",
          "parent_name",
          "supplier_name",
        ],
      },
      {
        name: "color_count",
        label: "Colors",
        type: "number",
      },
      {
        name: "die_station_count",
        label: "Die Stations",
        type: "number",
      },
      {
        name: "max_web_width_inches",
        label: "Max Web",
        type: "number",
        step: "0.0001",
      },
      {
        name: "printer_ip",
        label: "Printer IP",
        type: "text",
        placeholder: "192.168.1.128",
      },
      {
        name: "printer_port",
        label: "Printer Port",
        type: "number",
        step: "1",
        defaultValue: 9100,
      },
      {
        name: "printer_speed",
        label: "Printer Speed",
        type: "text",
        defaultValue: "5",
      },
      {
        name: "printer_darkness",
        label: "Printer Darkness",
        type: "text",
        defaultValue: "11",
      },
      {
        name: "printer_queue_key",
        label: "Printer Queue Key",
        type: "text",
        placeholder: "ETI",
      },
      {
        name: "has_digital_print",
        label: "Digital",
        type: "checkbox",
      },
      {
        name: "has_undercut_capability",
        label: "Undercut",
        type: "checkbox",
      },
      {
        name: "has_perf_capability",
        label: "Perf",
        type: "checkbox",
      },
      {
        name: "is_active",
        label: "Active",
        type: "checkbox",
        defaultValue: true,
      },
      {
        name: "notes",
        label: "Notes",
        type: "textarea",
      },
    ],
  },

  {
    key: "locations",
    endpoint: "locations",
    label: "Locations",
    singular: "Location",
    group: "plant",
    icon: MapPin,
    accent: "#22c55e",
    defaultOrdering: "name,code",
    tagline: "Plant, warehouse, shelf, drawer, and tooling storage map.",
    viewMode: "locations",
    columns: [
      "name",
      "code",
      "location_type",
      "parent_name",
      "is_active",
    ],
    fields: [
      {
        name: "name",
        label: "Name",
        type: "text",
        required: true,
      },
      {
        name: "code",
        label: "Code",
        type: "text",
      },
      {
        name: "location_type",
        label: "Type",
        type: "select",
        choices: choiceLists.locationType,
      },
      {
        name: "parent",
        label: "Parent",
        type: "searchRelation",
        relation: "locations",
        searchable: true,
        searchFields: [
          "name",
          "code",
          "location_type",
          "parent_name",
        ],
      },
      {
        name: "is_active",
        label: "Active",
        type: "checkbox",
        defaultValue: true,
      },
      {
        name: "notes",
        label: "Notes",
        type: "textarea",
      },
    ],
  },

  {
    key: "suppliers",
    endpoint: "suppliers",
    label: "Suppliers",
    singular: "Supplier",
    group: "plant",
    icon: Store,
    accent: "#fde68a",
    defaultOrdering: "name",
    tagline: "Supplier contact list for tooling purchases, repairs, and references.",
    columns: [
      "name",
      "tags",
      "phone",
      "email",
      "city",
      "state",
      "is_active",
    ],
    fields: [
      {
        name: "name",
        label: "Name",
        type: "text",
        required: true,
      },
      {
        name: "phone",
        label: "Phone",
        type: "text",
      },
      {
        name: "email",
        label: "Email",
        type: "email",
      },
      {
        name: "tags",
        label: "Tags",
        type: "text",
        placeholder: "tooling, material, box, core",
        helpText: "Comma-separated tags recommend this supplier in matching forms.",
      },
      {
        name: "city",
        label: "City",
        type: "text",
      },
      {
        name: "state",
        label: "State",
        type: "text",
      },
      {
        name: "zip_code",
        label: "Zip",
        type: "text",
      },
      {
        name: "is_active",
        label: "Active",
        type: "checkbox",
        defaultValue: true,
      },
      {
        name: "notes",
        label: "Notes",
        type: "textarea",
      },
    ],
  },

  {
    key: "history",
    endpoint: "history",
    label: "History",
    singular: "History Event",
    group: "trace",
    icon: History,
    accent: "#94a3b8",
    defaultOrdering: "-event_date",
    tagline: "Movement, inspection, repair, and lifecycle records.",
    columns: [
      "event_date",
      "event_type",
      "tool_label",
      "press_name",
      "from_location_name",
      "to_location_name",
    ],
    fields: [
      {
        name: "event_date",
        label: "Event Date",
        type: "date",
      },
      {
        name: "event_type",
        label: "Event Type",
        type: "text",
      },
      {
        name: "mag",
        label: "Mag",
        type: "searchRelation",
        relation: "mags",
        searchable: true,
        searchFields: [
          "name",
          "tooth_count",
          "repeat_inches",
          "face_width_inches",
          "status",
          "current_location_name",
        ],
      },
      {
        name: "flex_die",
        label: "Flex Die",
        type: "searchRelation",
        relation: "flex-dies",
        searchable: true,
        searchFields: [
          "name",
          "tool_number",
          "gear",
          "number_across",
          "number_around",
          "status",
          "current_location_name",
        ],
      },
      {
        name: "perf_cylinder",
        label: "Perf Cylinder",
        type: "searchRelation",
        relation: "perf-cylinders",
        searchable: true,
        searchFields: [
          "name",
          "gear_tooth_count",
          "status",
          "current_location_name",
        ],
      },
      {
        name: "press",
        label: "Press",
        type: "searchRelation",
        relation: "presses",
        searchable: true,
        searchFields: [
          "name",
          "location_name",
          "location_full_path",
        ],
      },
      {
        name: "from_location",
        label: "From",
        type: "searchRelation",
        relation: "locations",
        searchable: true,
        searchFields: [
          "name",
          "code",
          "location_type",
          "parent_name",
        ],
      },
      {
        name: "to_location",
        label: "To",
        type: "searchRelation",
        relation: "locations",
        searchable: true,
        searchFields: [
          "name",
          "code",
          "location_type",
          "parent_name",
        ],
      },
      {
        name: "supplier",
        label: "Supplier",
        type: "searchRelation",
        relation: "suppliers",
        searchable: true,
        searchFields: [
          "name",
          "phone",
          "email",
          "city",
          "state",
        ],
      },
      {
        name: "notes",
        label: "Notes",
        type: "textarea",
      },
    ],
  },
];

export const resourceMap = Object.fromEntries(
  resources.map((item) => [item.key, item])
);
