# Generated by Django 6.0.4 on 2026-05-06 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('tooling', '0006_alter_flexdie_shape_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=80, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('job_name', models.CharField(max_length=150)),
                ('product_code', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('in_production', 'In Production'), ('finishing', 'Finishing'), ('complete', 'Complete'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('rush', 'Rush'), ('hot', 'Hot')], default='normal', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('label_width_inches', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('label_length_inches', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('labels_across', models.PositiveIntegerField(blank=True, null=True)),
                ('labels_around', models.PositiveIntegerField(blank=True, null=True)),
                ('face_type', models.CharField(blank=True, max_length=100)),
                ('liner_type', models.CharField(blank=True, max_length=100)),
                ('requested_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('produced_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('finishing_type', models.CharField(choices=[('rolls', 'Rolls'), ('fanfold', 'Fanfold'), ('sheeted', 'Sheeted'), ('carton_only', 'Carton Only'), ('custom', 'Custom')], default='rolls', max_length=30)),
                ('labels_per_unit', models.PositiveIntegerField(blank=True, null=True)),
                ('units_per_carton', models.PositiveIntegerField(blank=True, null=True)),
                ('cartons_required', models.PositiveIntegerField(blank=True, null=True)),
                ('core_size_inches', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('wind_direction', models.CharField(blank=True, choices=[('', 'Not Set'), ('1', 'Wind 1'), ('2', 'Wind 2'), ('3', 'Wind 3'), ('4', 'Wind 4'), ('5', 'Wind 5'), ('6', 'Wind 6'), ('7', 'Wind 7'), ('8', 'Wind 8')], max_length=5)),
                ('finishing_notes', models.TextField(blank=True)),
                ('operator', models.CharField(blank=True, max_length=100)),
                ('suboperator', models.CharField(blank=True, max_length=100)),
                ('production_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_inventory', models.ForeignKey(blank=True, help_text='The coated stock or roll selected for the job.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_tickets', to='materials.rawmaterialinventory')),
                ('press', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_job_tickets', to='tooling.press')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_job_tickets', to='tooling.toolingrecipe')),
                ('recipe_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_job_tickets', to='tooling.toolingrecipeoption')),
            ],
            options={
                'ordering': ['-scheduled_date', 'ticket_number'],
            },
        ),
        migrations.CreateModel(
            name='FinishedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('material_width_inches', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('material_length_feet', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('face_type', models.CharField(blank=True, max_length=100)),
                ('liner_type', models.CharField(blank=True, max_length=100)),
                ('liner_serial_number', models.CharField(blank=True, max_length=80)),
                ('face_serial_number', models.CharField(blank=True, max_length=80)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit', models.CharField(choices=[('roll', 'Roll'), ('carton', 'Carton'), ('case', 'Case'), ('label', 'Label'), ('sheet', 'Sheet'), ('each', 'Each')], default='roll', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('allocated', 'Allocated'), ('shipped', 'Shipped'), ('on_hold', 'On Hold'), ('scrapped', 'Scrapped')], default='available', max_length=20)),
                ('operator', models.CharField(blank=True, max_length=100)),
                ('suboperator', models.CharField(blank=True, max_length=100)),
                ('run_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_finished_inventory', to='tooling.toolinglocation')),
                ('material_inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_inventory', to='materials.rawmaterialinventory')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_finished_inventory', to='tooling.toolingrecipe')),
                ('recipe_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_finished_inventory', to='tooling.toolingrecipeoption')),
                ('job_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_inventory', to='production.jobticket')),
            ],
            options={
                'ordering': ['-run_date', 'name'],
            },
        ),
    ]
