# Generated by Django 6.0.4 on 2026-05-06 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_materialspec_options_and_more'),
        ('production', '0001_initial'),
        ('tooling', '0006_alter_flexdie_shape_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobticket',
            options={'ordering': ['ticket_number']},
        ),
        migrations.RemoveField(
            model_name='jobticket',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='jobticket',
            name='material_inventory',
        ),
        migrations.RemoveField(
            model_name='jobticket',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='jobticket',
            name='press',
        ),
        migrations.RemoveField(
            model_name='jobticket',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='jobticket',
            name='produced_quantity',
        ),
        migrations.RemoveField(
            model_name='jobticket',
            name='production_notes',
        ),
        migrations.RemoveField(
            model_name='jobticket',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='jobticket',
            name='status',
        ),
        migrations.RemoveField(
            model_name='jobticket',
            name='suboperator',
        ),
        migrations.AddField(
            model_name='jobticket',
            name='job_notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ProductionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_po', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('unscheduled', 'Unscheduled'), ('scheduled', 'Scheduled'), ('ready', 'Ready'), ('running', 'Running'), ('complete', 'Complete'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='unscheduled', max_length=30)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('rush', 'Rush'), ('hot', 'Hot')], default='normal', max_length=20)),
                ('quantity_to_ship', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantity_to_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('material_width_inches', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=100)),
                ('suboperator', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='production.jobticket')),
                ('material_inventory', models.ForeignKey(blank=True, help_text='The coated stock or roll selected for this scheduled run.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_schedule', to='materials.rawmaterialinventory')),
                ('press', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_schedule', to='tooling.press')),
            ],
            options={
                'ordering': ['scheduled_date', 'priority', 'job_ticket__ticket_number'],
            },
        ),
    ]
