# Generated by Django 6.0.4 on 2026-05-08 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_materialspec_gsm'),
        ('production', '0002_alter_jobticket_options_remove_jobticket_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='box_height_inches',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='box_length_inches',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='box_width_inches',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='cutting_type',
            field=models.CharField(choices=[('to_liner', 'To Liner'), ('metal_to_metal', 'Metal to Metal'), ('score', 'Score'), ('special', 'Special')], default='to_liner', max_length=30),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='material_spec',
            field=models.ForeignKey(blank=True, help_text='The finished raw material family/spec this job should run on. Specific inventory rolls are assigned on the production schedule.', limit_choices_to={'material_type': 'coated_stock'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_tickets', to='materials.materialspec'),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='repeat_inches',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
