# Generated by Django 6.0.4 on 2026-05-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_jobticket_box_height_inches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobticket',
            name='labels_across',
        ),
        migrations.RemoveField(
            model_name='jobticket',
            name='labels_around',
        ),
    ]
