# Generated by Django 6.0.4 on 2026-05-08 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_remove_jobticket_labels_across_and_more'),
        ('tooling', '0006_alter_flexdie_shape_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('item_number', models.CharField(blank=True, max_length=80)),
                ('supplier', models.CharField(blank=True, max_length=150)),
                ('width_inches', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('length_inches', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('height_inches', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['supplier', 'name', 'item_number'],
            },
        ),
        migrations.RemoveField(
            model_name='jobticket',
            name='box_height_inches',
        ),
        migrations.RemoveField(
            model_name='jobticket',
            name='box_length_inches',
        ),
        migrations.RemoveField(
            model_name='jobticket',
            name='box_width_inches',
        ),
        migrations.RemoveField(
            model_name='jobticket',
            name='cartons_required',
        ),
        migrations.RemoveField(
            model_name='jobticket',
            name='recipe_option',
        ),
        migrations.AlterField(
            model_name='jobticket',
            name='finishing_type',
            field=models.CharField(choices=[('rolls', 'Rolls'), ('fanfold', 'Fanfold'), ('sheeted', 'Sheeted')], default='rolls', max_length=30),
        ),
        migrations.CreateModel(
            name='BoxInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(blank=True, max_length=80)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('scheduled', 'Scheduled'), ('allocated', 'Allocated'), ('on_hold', 'On Hold'), ('depleted', 'Depleted'), ('scrapped', 'Scrapped')], default='available', max_length=20)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_inventory', to='tooling.toolinglocation')),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='production.boxspec')),
            ],
            options={
                'ordering': ['box__name', 'lot_number'],
            },
        ),
        migrations.AddField(
            model_name='jobticket',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_tickets', to='production.boxspec'),
        ),
    ]
