# Generated by Django 6.0.4 on 2026-05-08 18:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_boxspec_remove_jobticket_box_height_inches_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('customer_code', models.CharField(blank=True, max_length=80)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='productionschedule',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='productionschedule',
            name='planned_end',
        ),
        migrations.RemoveField(
            model_name='productionschedule',
            name='planned_start',
        ),
        migrations.RemoveField(
            model_name='productionschedule',
            name='press',
        ),
        migrations.RemoveField(
            model_name='productionschedule',
            name='suboperator',
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_tickets', to='production.customer'),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='production.customer'),
        ),
    ]
