# Generated by Django 6.0.4 on 2026-05-08 18:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_customer_remove_productionschedule_operator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('customer_po', models.CharField(blank=True, max_length=100)),
                ('job_name', models.CharField(blank=True, max_length=150)),
                ('product_code', models.CharField(blank=True, max_length=80)),
                ('quantity_to_ship', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantity_to_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('order_date', models.DateField(default=django.utils.timezone.localdate)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('rush', 'Rush'), ('hot', 'Hot')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ready', 'Ready'), ('running', 'Running'), ('complete', 'Complete'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('schedule_removed', 'Schedule Removed')], default='scheduled', max_length=30)),
                ('operator_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='production.customer')),
                ('job_ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='production.jobticket')),
                ('schedule_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='production.productionschedule')),
            ],
            options={
                'ordering': ['-order_date', '-scheduled_date', 'customer_name', 'job_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=255)),
                ('performed_by', models.CharField(default='system', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='production.customerorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
