# Generated by Django 6.0.4 on 2026-05-18 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_customerorder_customerorderevent'),
        ('tooling', '0007_jobticket_cover_image_jobticket_finishing_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='actual_footage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='footage_report',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='operator',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='press_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='press_sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='scheduled_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='actual_footage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='footage_report',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='operator',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='press',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_schedule', to='tooling.press'),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='press_sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='scheduled_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('unscheduled', 'Unscheduled'), ('scheduled', 'Scheduled'), ('ready', 'Ready'), ('running', 'Running'), ('complete', 'Complete'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('schedule_removed', 'Schedule Removed')], default='scheduled', max_length=30),
        ),
    ]
