# Generated by Django 6.0.4 on 2026-05-18 14:56

import django.db.models.deletion
import django.utils.timezone
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


DEFAULT_ROLES = [
    ("Admin", "Full system access", ["*"], True),
    ("Sales", "Quote calculator only", ["quote-calculator"], False),
    ("CSR", "Customer service quoting, tickets, and scheduling", ["quote-calculator", "customers", "job-tickets", "production-schedule", "customer-orders"], False),
    ("Production", "Production queue, job details, and press workflow", ["production-schedule", "job-tickets", "customer-orders", "presses"], False),
    ("Manager", "Management access", ["*"], False),
]


def seed_company_access(apps, schema_editor):
    CompanyRole = apps.get_model("production", "CompanyRole")
    CompanyUser = apps.get_model("production", "CompanyUser")

    roles = {}
    for name, description, allowed_resource_keys, locked in DEFAULT_ROLES:
        role, _ = CompanyRole.objects.update_or_create(
            name=name,
            defaults={
                "description": description,
                "allowed_resource_keys": allowed_resource_keys,
                "locked": locked,
            },
        )
        roles[name] = role

    admin = CompanyUser.objects.filter(username__iexact="admin").first()
    if not admin:
        CompanyUser.objects.create(
            username="admin",
            name="Admin",
            password_hash=make_password("Bluelabels7&"),
            role=roles["Admin"],
            active=True,
        )
    else:
        admin.name = admin.name or "Admin"
        admin.role = roles["Admin"]
        admin.active = True
        if not admin.password_hash:
            admin.password_hash = make_password("Bluelabels7&")
        admin.save()


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_customerorder_actual_footage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('allowed_resource_keys', models.JSONField(blank=True, default=list)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteFinishedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('source_type', models.CharField(default='made', max_length=40)),
                ('purchased_msi_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('face_raw_id', models.CharField(blank=True, max_length=120)),
                ('liner_raw_id', models.CharField(blank=True, max_length=120)),
                ('adhesive_raw_id', models.CharField(blank=True, max_length=120)),
                ('silicone_raw_id', models.CharField(blank=True, max_length=120)),
                ('ink_raw_id', models.CharField(blank=True, max_length=120)),
                ('labor_msi_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('coating_msi_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('complexity_msi_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('other_msi_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('component_type', models.CharField(default='face', max_length=40)),
                ('msi_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('inventory_msi', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['component_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('password_hash', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='production.companyrole')),
            ],
            options={
                'ordering': ['name', 'username'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('quote_number', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prepared_by_user_id', models.CharField(blank=True, max_length=120)),
                ('prepared_by_username', models.CharField(blank=True, max_length=80)),
                ('prepared_by_name', models.CharField(blank=True, max_length=150)),
                ('prepared_by_role', models.CharField(blank=True, max_length=80)),
                ('job_ticket_number', models.CharField(blank=True, max_length=80)),
                ('customer_name', models.CharField(blank=True, max_length=180)),
                ('job_name', models.CharField(blank=True, max_length=180)),
                ('product_code', models.CharField(blank=True, max_length=80)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('prepared_by', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('material_name', models.CharField(blank=True, max_length=180)),
                ('material_source', models.CharField(blank=True, max_length=40)),
                ('material_components', models.TextField(blank=True)),
                ('form', models.JSONField(blank=True, default=dict)),
                ('pricing', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_records', to='production.jobticket')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RunPython(seed_company_access, migrations.RunPython.noop),
    ]
