# Generated by Django 6.0.4 on 2026-05-18 17:31

from django.db import migrations, models


def seed_quote_cost_rates(apps, schema_editor):
    QuoteCostRate = apps.get_model("production", "QuoteCostRate")
    defaults = [
        ("labor", "Labor", "0.0000", "Added to every made in-house finished material."),
        ("color", "Color / Ink", "0.0300", "Multiplied by the number of colors on a quote item."),
        ("coating", "Coating", "0.0000", "Multiplied by the number of coatings on a quote item."),
    ]
    for key, label, msi_cost, notes in defaults:
        QuoteCostRate.objects.update_or_create(
            key=key,
            defaults={
                "label": label,
                "msi_cost": msi_cost,
                "notes": notes,
                "locked": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_companyrole_quotefinishedmaterial_quoterawmaterial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteCostRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('msi_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('locked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='jobticket',
            name='labels_per_carton',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotefinishedmaterial',
            name='base_markup_percent',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='quotefinishedmaterial',
            name='target_margin_percent',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.RunPython(seed_quote_cost_rates, migrations.RunPython.noop),
    ]
