# Generated by Django 6.0.4 on 2026-05-19 11:19

import production.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_rename_target_margin_to_target_markup'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='finishing_image',
            field=models.ImageField(blank=True, null=True, upload_to=production.models.job_ticket_image_upload_path),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='finishing_image_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='finishing_image_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='general_image',
            field=models.ImageField(blank=True, null=True, upload_to=production.models.job_ticket_image_upload_path),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='general_image_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='general_image_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='spec_image',
            field=models.ImageField(blank=True, null=True, upload_to=production.models.job_ticket_image_upload_path),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='spec_image_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='spec_image_name',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
