# Generated by Django 6.0.4 on 2026-05-27 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_jobticket_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='finishedinventory',
            name='customer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_inventory', to='production.customerorder'),
        ),
        migrations.AddField(
            model_name='finishedinventory',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
