# Generated by Django 6.0.4 on 2026-05-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_customerorder_order_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveFootageArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(db_index=True, unique=True)),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('total_footage', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('goal_footage', models.DecimalField(decimal_places=2, default=400000, max_digits=14)),
                ('press_totals', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-shift_date'],
            },
        ),
    ]
