# Generated by Codex on 2026-06-03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0023_livefootagearchive"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="customer",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="customer",
            name="address_line_3",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="country",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="customer",
            name="postal_code",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="customer",
            name="state",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="quoterecord",
            name="customer",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="quote_records", to="production.customer"),
        ),
    ]
