# Generated by Codex on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0024_customer_address_quote_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotefinishedmaterial",
            name="unit_type",
            field=models.CharField(choices=[("label", "Label"), ("tag", "Tag")], default="label", max_length=20),
        ),
    ]
