# Generated by Django 6.0.4 on 2026-06-25 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0029_quote_workflow_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('participant_user_ids', models.JSONField(blank=True, default=list)),
                ('participant_names', models.JSONField(blank=True, default=list)),
                ('context_type', models.CharField(blank=True, max_length=60)),
                ('context_id', models.CharField(blank=True, max_length=120)),
                ('context_label', models.CharField(blank=True, max_length=220)),
                ('created_by_user_id', models.CharField(blank=True, max_length=120)),
                ('created_by_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_user_id', models.CharField(blank=True, max_length=120)),
                ('sender_name', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField()),
                ('read_by_user_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='production.messagethread')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
