# Generated by Django 6.0.4 on 2026-07-01 15:08

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_roll_documentation_and_job_usage'),
        ('production', '0033_add_material_handling_access'),
        ('tooling', '0013_press_printer_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionShiftSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Plant Reporting Day', max_length=80, unique=True)),
                ('shift_start_time', models.TimeField(default=datetime.time(3, 0))),
                ('shift_end_time', models.TimeField(default=datetime.time(3, 0))),
                ('end_on_next_day', models.BooleanField(default=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='target_footage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Planned linear footage for operator progress and shift handoff.', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='ProductionMaterialAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('tsm', 'Tri-State Media Roll'), ('outsourced', 'Purchased Roll')], max_length=20)),
                ('carton_lot_code', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Enter the 5-digit lot number stamped on the cartons.')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('complete', 'Used'), ('rejected', 'Quality Hold'), ('removed', 'Removed')], default='active', max_length=20)),
                ('assigned_by', models.CharField(blank=True, max_length=120)),
                ('quality_note', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_assignments', to='materials.rawmaterialinventory')),
                ('production_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_assignments', to='production.productionschedule')),
            ],
            options={
                'ordering': ['-assigned_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=120)),
                ('report_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('total_footage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('good_footage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('material_footage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outcome', models.CharField(choices=[('end_shift', 'End of Shift'), ('job_complete', 'Job Complete')], default='end_shift', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_reports', to='production.jobticket')),
                ('press', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_reports', to='tooling.press')),
                ('production_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_reports', to='production.productionschedule')),
            ],
            options={
                'ordering': ['-report_date', '-shift_end', '-id'],
            },
        ),
    ]
