# Generated by Django 6.0.4 on 2026-08-25 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0042_customer_followup_history_and_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinteraction',
            name='address_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='address_line_3',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='address_matches_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='contact_matches_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='contact_role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='postal_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('address_line_1', models.CharField(blank=True, max_length=180)),
                ('address_line_2', models.CharField(blank=True, max_length=180)),
                ('address_line_3', models.CharField(blank=True, max_length=180)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_from_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.customerinteraction')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='production.customer')),
            ],
            options={
                'ordering': ['-is_primary', 'label', 'city', 'state', 'id'],
            },
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='customer_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='production.customeraddress'),
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_from_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.customerinteraction')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='production.customer')),
            ],
            options={
                'ordering': ['-is_primary', 'last_name', 'first_name', 'email', 'id'],
            },
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='customer_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='production.customercontact'),
        ),
    ]
