# Generated by Django 6.0.4 on 2026-08-25 15:28

from django.db import migrations, models


def migrate_priority_values(apps, schema_editor):
    value_map = {
        "normal": "low",
        "rush": "medium",
        "hot": "high",
    }
    for model_name in ("CustomerOrder", "ProductionSchedule"):
        model = apps.get_model("production", model_name)
        for old_value, new_value in value_map.items():
            model.objects.filter(priority=old_value).update(priority=new_value)


def restore_priority_values(apps, schema_editor):
    value_map = {
        "low": "normal",
        "medium": "rush",
        "high": "hot",
    }
    for model_name in ("CustomerOrder", "ProductionSchedule"):
        model = apps.get_model("production", model_name)
        for old_value, new_value in value_map.items():
            model.objects.filter(priority=old_value).update(priority=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0043_customerinteraction_address_label_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_priority_values, restore_priority_values),
        migrations.AlterField(
            model_name='customerorder',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
    ]
