# Generated by Django 6.0.4 on 2026-08-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0044_schedule_priority_low_medium_high'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionschedule',
            name='held_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='held_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='hold_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='hold_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
