# Generated by Django 6.0.4 on 2026-08-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0026_materialusage_materials_m_finishe_70178c_idx_and_more'),
        ('production', '0045_production_schedule_hold_reasons'),
        ('tooling', '0020_flexdierequest_toolinghistory_die_request_closed'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['job_ticket', '-order_date'], name='production__job_tic_346397_idx'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['customer', '-order_date'], name='production__custome_dfec34_idx'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['product_code'], name='production__product_ed465c_idx'),
        ),
        migrations.AddIndex(
            model_name='customerorderevent',
            index=models.Index(fields=['order', '-created_at'], name='production__order_i_423064_idx'),
        ),
        migrations.AddIndex(
            model_name='finishedinventory',
            index=models.Index(fields=['job_ticket', 'status', '-run_date'], name='production__job_tic_b80ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='finishedinventory',
            index=models.Index(fields=['status', '-run_date'], name='production__status_72f5bd_idx'),
        ),
        migrations.AddIndex(
            model_name='finishedinventory',
            index=models.Index(fields=['sku'], name='production__sku_59c72e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobticket',
            index=models.Index(fields=['product_code'], name='production__product_c1f7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='jobticket',
            index=models.Index(fields=['repeat_inches'], name='production__repeat__ac7a92_idx'),
        ),
        migrations.AddIndex(
            model_name='jobticket',
            index=models.Index(fields=['material_master_type', 'repeat_inches'], name='production__materia_f5910d_idx'),
        ),
        migrations.AddIndex(
            model_name='jobticketevent',
            index=models.Index(fields=['job_ticket', '-created_at'], name='production__job_tic_02ce4c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobticketusage',
            index=models.Index(fields=['job_ticket', '-used_at'], name='production__job_tic_722e85_idx'),
        ),
        migrations.AddIndex(
            model_name='jobticketusage',
            index=models.Index(fields=['legacy_job_ticket_id', '-used_at'], name='production__legacy__f36473_idx'),
        ),
        migrations.AddIndex(
            model_name='productionschedule',
            index=models.Index(fields=['job_ticket', 'status', 'scheduled_date'], name='production__job_tic_96ca21_idx'),
        ),
        migrations.AddIndex(
            model_name='productionschedule',
            index=models.Index(fields=['status', 'scheduled_date'], name='production__status_881cb7_idx'),
        ),
    ]
