# Generated by Django 6.0.4 on 2026-08-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0046_customerorder_production__job_tic_346397_idx_and_more'),
        ('tooling', '0021_flexdie_compatible_presses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='art_file_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='art_file_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='art_file_created_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='has_print',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='print_method',
            field=models.CharField(choices=[('none', 'No Print'), ('static', 'Static Plates'), ('digital_static', 'Digital Static'), ('dynamic', 'Dynamic / Variable')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='print_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='print_plates',
            field=models.ManyToManyField(blank=True, help_text='Static print plates tied directly to this job ticket.', related_name='job_tickets', to='tooling.printplate'),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='dynamic_end_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='dynamic_file_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='dynamic_file_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='dynamic_start_number',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
