# Generated by Django 6.0.4 on 2026-05-06 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tooling', '0006_alter_flexdie_shape_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('liner', 'Liner'), ('face', 'Face'), ('adhesive', 'Adhesive'), ('silicone', 'Silicone'), ('coating', 'Coating'), ('coated_stock', 'Coated Stock')], max_length=30)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('liner_pounds', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('thickness_mil', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('width_inches', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('face_type', models.CharField(blank=True, max_length=100)),
                ('liner_type', models.CharField(blank=True, max_length=100)),
                ('adhesive_type', models.CharField(blank=True, max_length=100)),
                ('silicone_type', models.CharField(blank=True, max_length=100)),
                ('coating_type', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_specs', to='tooling.supplier')),
            ],
            options={
                'ordering': ['material_type', 'company', 'name', 'width_inches'],
            },
        ),
        migrations.CreateModel(
            name='CoaterRollTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('complete', 'Complete'), ('on_hold', 'On Hold'), ('void', 'Void')], default='scheduled', max_length=20)),
                ('print_status', models.CharField(choices=[('not_printed', 'Not Printed'), ('queued', 'Queued'), ('printed', 'Printed'), ('reprint', 'Needs Reprint')], default='not_printed', max_length=20)),
                ('scheduled_by', models.CharField(blank=True, max_length=100)),
                ('result_code', models.CharField(blank=True, max_length=80)),
                ('result_serial_number', models.CharField(blank=True, max_length=80)),
                ('result_lot_number', models.CharField(blank=True, max_length=80)),
                ('width_inches', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('length_feet', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('weight_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('operator', models.CharField(blank=True, max_length=100)),
                ('run_date', models.DateField(blank=True, null=True)),
                ('log_inventory', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coater_roll_tags', to='tooling.toolinglocation')),
                ('adhesive', models.ForeignKey(limit_choices_to={'material_type': 'adhesive'}, on_delete=django.db.models.deletion.PROTECT, related_name='coater_adhesive_tags', to='materials.materialspec')),
                ('coating', models.ForeignKey(blank=True, limit_choices_to={'material_type': 'coating'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coater_coating_tags', to='materials.materialspec')),
                ('face', models.ForeignKey(limit_choices_to={'material_type': 'face'}, on_delete=django.db.models.deletion.PROTECT, related_name='coater_face_tags', to='materials.materialspec')),
                ('liner', models.ForeignKey(limit_choices_to={'material_type': 'liner'}, on_delete=django.db.models.deletion.PROTECT, related_name='coater_liner_tags', to='materials.materialspec')),
                ('produced_material', models.ForeignKey(blank=True, limit_choices_to={'material_type': 'coated_stock'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_roll_tags', to='materials.materialspec')),
                ('scheduled_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_roll_tags', to='materials.materialspec')),
                ('silicone', models.ForeignKey(limit_choices_to={'material_type': 'silicone'}, on_delete=django.db.models.deletion.PROTECT, related_name='coater_silicone_tags', to='materials.materialspec')),
            ],
            options={
                'ordering': ['-run_date', 'tag_number'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('liner', 'Liner'), ('face', 'Face'), ('adhesive', 'Adhesive'), ('silicone', 'Silicone'), ('coating', 'Coating'), ('coated_stock', 'Coated Stock')], default='coated_stock', max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=80)),
                ('serial_number', models.CharField(blank=True, max_length=80)),
                ('lot_number', models.CharField(blank=True, max_length=80)),
                ('width_inches', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('length_feet', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('weight_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit', models.CharField(choices=[('lf', 'Linear Feet'), ('msi', 'MSI'), ('lbs', 'Pounds'), ('gal', 'Gallons'), ('roll', 'Roll'), ('each', 'Each')], default='lf', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('scheduled', 'Scheduled'), ('allocated', 'Allocated'), ('in_use', 'In Use'), ('on_hold', 'On Hold'), ('depleted', 'Depleted'), ('scrapped', 'Scrapped')], default='available', max_length=20)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_inventory', to='tooling.toolinglocation')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='materials.materialspec')),
                ('source_roll_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_entries', to='materials.coaterrolltag')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_inventory', to='tooling.supplier')),
            ],
            options={
                'ordering': ['material_type', 'name', 'serial_number'],
            },
        ),
        migrations.AddField(
            model_name='coaterrolltag',
            name='logged_inventory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_roll_tag', to='materials.rawmaterialinventory'),
        ),
    ]
