# Generated by Django 6.0.4 on 2026-05-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialspec',
            options={'ordering': ['material_type', 'company', 'name', 'code']},
        ),
        migrations.RemoveField(
            model_name='materialspec',
            name='adhesive_type',
        ),
        migrations.RemoveField(
            model_name='materialspec',
            name='coating_type',
        ),
        migrations.RemoveField(
            model_name='materialspec',
            name='face_type',
        ),
        migrations.RemoveField(
            model_name='materialspec',
            name='liner_type',
        ),
        migrations.RemoveField(
            model_name='materialspec',
            name='silicone_type',
        ),
        migrations.RemoveField(
            model_name='materialspec',
            name='thickness_mil',
        ),
        migrations.RemoveField(
            model_name='materialspec',
            name='width_inches',
        ),
        migrations.AddField(
            model_name='materialspec',
            name='material_family',
            field=models.CharField(blank=True, help_text='User-defined family/type, such as SCK liner, PolyMatte face, removable adhesive, or easy-release silicone.', max_length=100),
        ),
    ]
