# Generated by Django 6.0.4 on 2026-05-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_materialspec_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialspec',
            name='gsm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
