# Generated by Django 6.0.4 on 2026-05-08 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_materialspec_gsm'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialspec',
            name='adhesive_material',
            field=models.ForeignKey(blank=True, limit_choices_to={'material_type': 'adhesive'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_adhesive_materials', to='materials.materialspec'),
        ),
        migrations.AddField(
            model_name='materialspec',
            name='coater_cut_plan',
            field=models.CharField(blank=True, help_text='Cut plan operators should run, such as 3 x 13 in or 2 x 6.5 in.', max_length=200),
        ),
        migrations.AddField(
            model_name='materialspec',
            name='coating_material',
            field=models.ForeignKey(blank=True, limit_choices_to={'material_type': 'coating'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_coating_materials', to='materials.materialspec'),
        ),
        migrations.AddField(
            model_name='materialspec',
            name='face_material',
            field=models.ForeignKey(blank=True, limit_choices_to={'material_type': 'face'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_face_materials', to='materials.materialspec'),
        ),
        migrations.AddField(
            model_name='materialspec',
            name='liner_material',
            field=models.ForeignKey(blank=True, limit_choices_to={'material_type': 'liner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_liner_materials', to='materials.materialspec'),
        ),
        migrations.AddField(
            model_name='materialspec',
            name='operator_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='materialspec',
            name='scheduled_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='materialspec',
            name='silicone_material',
            field=models.ForeignKey(blank=True, limit_choices_to={'material_type': 'silicone'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_silicone_materials', to='materials.materialspec'),
        ),
        migrations.AddField(
            model_name='materialspec',
            name='target_run_length_feet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
