# Generated by Django 6.0.4 on 2026-05-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_materialspec_adhesive_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialinventory',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
