# Generated by Codex on 2026-05-11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_rawmaterialinventory_name"),
        ("production", "0007_customerorder_customerorderevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("checkout", "Checked Out"),
                            ("returned", "Returned"),
                            ("qc_issue", "QC Issue"),
                            ("coater", "Coater"),
                            ("finished", "Finished Production"),
                            ("manual", "Manual Consumption"),
                            ("scrap", "Scrap"),
                            ("adjustment", "Adjustment"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("lf", "Linear Feet"),
                            ("msi", "MSI"),
                            ("lbs", "Pounds"),
                            ("gal", "Gallons"),
                            ("roll", "Roll"),
                            ("each", "Each"),
                        ],
                        default="lf",
                        max_length=20,
                    ),
                ),
                ("used_date", models.DateField(default=django.utils.timezone.localdate)),
                ("used_by", models.CharField(blank=True, max_length=120)),
                ("reference", models.CharField(blank=True, max_length=150)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coater_roll_tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_usages",
                        to="materials.coaterrolltag",
                    ),
                ),
                (
                    "finished_inventory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_usages",
                        to="production.finishedinventory",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_records",
                        to="materials.rawmaterialinventory",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_records",
                        to="materials.materialspec",
                    ),
                ),
            ],
            options={
                "ordering": ["-used_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="coaterrolltag",
            name="adhesive_inventory",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"material_type": "adhesive"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coater_adhesive_usages",
                to="materials.rawmaterialinventory",
            ),
        ),
        migrations.AddField(
            model_name="coaterrolltag",
            name="coating_inventory",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"material_type": "coating"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coater_coating_usages",
                to="materials.rawmaterialinventory",
            ),
        ),
        migrations.AddField(
            model_name="coaterrolltag",
            name="face_inventory",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"material_type": "face"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coater_face_usages",
                to="materials.rawmaterialinventory",
            ),
        ),
        migrations.AddField(
            model_name="coaterrolltag",
            name="liner_inventory",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"material_type": "liner"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coater_liner_usages",
                to="materials.rawmaterialinventory",
            ),
        ),
        migrations.AddField(
            model_name="coaterrolltag",
            name="silicone_inventory",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"material_type": "silicone"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coater_silicone_usages",
                to="materials.rawmaterialinventory",
            ),
        ),
    ]
