# Generated by Codex on 2026-05-11

from django.db import migrations


PREFIXES = {
    "liner": "LIN",
    "face": "FAC",
    "adhesive": "ADH",
    "silicone": "SIL",
    "coating": "COA",
    "coated_stock": "CS",
}


def populate_roll_ids(apps, schema_editor):
    inventory_model = apps.get_model("materials", "RawMaterialInventory")
    for roll in inventory_model.objects.filter(serial_number=""):
        prefix = PREFIXES.get(roll.material_type, "MAT")
        roll.serial_number = f"{prefix}-{roll.pk:06d}"
        roll.save(update_fields=["serial_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_materialusage_coaterrolltag_inventory_sources"),
    ]

    operations = [
        migrations.RunPython(populate_roll_ids, migrations.RunPython.noop),
    ]
