# Generated by Codex on 2026-05-11

from django.db import migrations, models


PREFIXES = {
    "liner": "LIN",
    "face": "FAC",
    "adhesive": "ADH",
    "silicone": "SIL",
    "coating": "COA",
    "coated_stock": "CS",
}


def populate_material_codes(apps, schema_editor):
    material_model = apps.get_model("materials", "MaterialSpec")
    for material in material_model.objects.filter(code=""):
        prefix = PREFIXES.get(material.material_type, "MAT")
        material.code = f"{prefix}-{material.pk:05d}"
        material.save(update_fields=["code"])


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_populate_inventory_roll_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialspec",
            name="code",
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
        migrations.RunPython(populate_material_codes, migrations.RunPython.noop),
    ]
