# Generated by Codex on 2026-05-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_materialspec_auto_code"),
    ]

    operations = []
