# Generated by Codex on 2026-05-11

import django.db.models.deletion
from django.db import migrations, models


def populate_tag_numbers(apps, schema_editor):
    tag_model = apps.get_model("materials", "CoaterRollTag")
    for tag in tag_model.objects.filter(tag_number=""):
        tag.tag_number = f"CRT-{tag.pk:06d}"
        tag.save(update_fields=["tag_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0009_checkout_usage_consumes_inventory"),
        ("tooling", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coaterrolltag",
            name="tag_number",
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
        migrations.AddField(
            model_name="coaterrolltag",
            name="cut_description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="coaterrolltag",
            name="operator_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="coaterrolltag",
            name="press",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coater_roll_tags",
                to="tooling.press",
            ),
        ),
        migrations.RunPython(populate_tag_numbers, migrations.RunPython.noop),
    ]
