# Generated by Django 6.0.4 on 2026-07-02 19:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


def populate_original_roll_footage(apps, schema_editor):
    RawMaterialInventory = apps.get_model("materials", "RawMaterialInventory")
    RawMaterialInventory.objects.filter(
        original_length_feet__isnull=True,
        length_feet__isnull=False,
    ).update(original_length_feet=models.F("length_feet"))


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_roll_documentation_and_job_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_code', models.CharField(max_length=80, unique=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('aisle', models.CharField(blank=True, max_length=40)),
                ('bay', models.CharField(blank=True, max_length=40)),
                ('level', models.CharField(blank=True, max_length=40)),
                ('position', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rack_code'],
            },
        ),
        migrations.AddField(
            model_name='rawmaterialinventory',
            name='original_length_feet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.RunPython(populate_original_roll_footage, migrations.RunPython.noop),
        migrations.CreateModel(
            name='MaterialSkid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skid_number', models.CharField(blank=True, max_length=80, unique=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired')], default='active', max_length=20)),
                ('other_location', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skids', to='materials.materialrack')),
            ],
            options={
                'ordering': ['-created_at', 'skid_number'],
            },
        ),
        migrations.AddField(
            model_name='rawmaterialinventory',
            name='current_skid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolls', to='materials.materialskid'),
        ),
        migrations.CreateModel(
            name='MaterialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('roll_created', 'Roll Created'), ('roll_registered', 'Roll Registered'), ('roll_assigned_to_skid', 'Roll Assigned to Skid'), ('roll_removed_from_skid', 'Roll Removed from Skid'), ('roll_added_back_to_skid', 'Roll Added Back to Skid'), ('roll_partially_used', 'Roll Partially Used'), ('roll_fully_used', 'Roll Fully Used'), ('skid_created', 'Skid Created'), ('skid_assigned_to_rack', 'Skid Assigned to Rack'), ('skid_removed_from_rack', 'Skid Removed from Rack'), ('rack_created', 'Rack Created'), ('label_printed', 'Label Printed'), ('label_reprinted', 'Label Reprinted'), ('manual_edit', 'Manual Edit')], max_length=40)),
                ('roll_reference', models.CharField(blank=True, max_length=100)),
                ('skid_reference', models.CharField(blank=True, max_length=100)),
                ('rack_reference', models.CharField(blank=True, max_length=100)),
                ('actor_name', models.CharField(blank=True, max_length=120)),
                ('actor_user_id', models.CharField(blank=True, max_length=120)),
                ('from_location', models.CharField(blank=True, max_length=180)),
                ('to_location', models.CharField(blank=True, max_length=180)),
                ('quantity_before', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('quantity_after', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('amount_used', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('scan', 'Scan'), ('manual', 'Manual'), ('system', 'System')], default='manual', max_length=20)),
                ('device_info', models.CharField(blank=True, max_length=500)),
                ('scan_session_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_history', to='materials.rawmaterialinventory')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_history', to='materials.materialrack')),
                ('skid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_history', to='materials.materialskid')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['action_type', '-created_at'], name='materials_m_action__9529eb_idx'), models.Index(fields=['scan_session_id'], name='materials_m_scan_se_2ae588_idx')],
            },
        ),
    ]
