# Generated by Django 6.0.4 on 2026-08-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0025_coaterrolltag_press_sequence'),
        ('production', '0045_production_schedule_hold_reasons'),
        ('tooling', '0020_flexdierequest_toolinghistory_die_request_closed'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='materialusage',
            index=models.Index(fields=['finished_inventory', 'usage_type', '-used_date'], name='materials_m_finishe_70178c_idx'),
        ),
        migrations.AddIndex(
            model_name='materialusage',
            index=models.Index(fields=['job_ticket', '-used_date'], name='materials_m_job_tic_7cd94f_idx'),
        ),
        migrations.AddIndex(
            model_name='materialusage',
            index=models.Index(fields=['material', '-used_date'], name='materials_m_materia_e80405_idx'),
        ),
        migrations.AddIndex(
            model_name='materialusage',
            index=models.Index(fields=['inventory', '-used_date'], name='materials_m_invento_e60953_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialinventory',
            index=models.Index(fields=['material_type', 'material', 'status'], name='materials_r_materia_d28e56_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialinventory',
            index=models.Index(fields=['material_type', 'status'], name='materials_r_materia_281180_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialinventory',
            index=models.Index(fields=['material', 'status'], name='materials_r_materia_b74c47_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialinventory',
            index=models.Index(fields=['code'], name='materials_r_code_18b258_idx'),
        ),
    ]
