# Generated by Django 6.0.4 on 2026-09-22 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0026_materialusage_materials_m_finishe_70178c_idx_and_more'),
        ('users', '0004_coater_role_uses_main_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialIntakeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_intake_receipts', to='users.companyuser')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'idempotency_key'), name='unique_material_intake_request')],
            },
        ),
    ]
